# GRPO AND SFT TRAINING NOTEBOOK

Author (2024-2025): Chengheng Li Chen (Template from Unsloth)

Second developer (2025-2026): Berta Fitó Casas

## 0. Initial checks on the environment (if not already known)

Provided that the code is being executed in a **local environment**, the user will need to set up an environment (*venv*) in which execute the following code. Alternatively (and probably easier), **Google Colab** can be used to run it. **Google Colab** is the intended platform for this code as of 2026.

#### Creating a Virtual Environment

To **create** a *venv* environment, the user may run the following command: `python -m venv <directory>`
- Where `<directory>` may be inputted from root or, after the user has accessed the desired directory (folder), input `.` (or the name of the new folder where the *venv* will reside) as `<directory>`

#### Activating a Virtual Environment

To **activate** a *venv*, find the Scripts folder within the indicated <directory> and execute the "activate" file in a terminal: `Scripts\activate.bat`

To **deactivate** a *venv*, find the Scripts folder within the indicated <directory> and execute the "activate" file in a terminal: `Scripts\deactivate.bat`

In [23]:
# [NOTE] Provided that the code is being executed in a local environment, NVIDA GPUs are not guaranteed (they are available in Google Colab)
#        Might require CUDA installation. Used link by second developer: https://developer.nvidia.com/cuda-12-1-0-download-archive

# If needed, the user can upgrade pip with the following command:
# %python -m pip install -U pip

import sys
import os
import platform

os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True" # To try and help PyTorch manage memory more efficiently
os.environ["ACCELERATE_NUM_PROCESSES"] = "1"                  # To ensure accelerate runs in single process mode

def get_env():
    is_colab = "google.colab" in sys.modules
    is_windows = platform.system() == "Windows"
    print(f"Environment: {'Colab' if is_colab else 'Local'} | OS: {platform.system()}") # PyTorch requires a Python version 3.8-3.12
    return is_colab, is_windows

IS_COLAB, IS_WINDOWS = get_env()

# Ensure PyTorch is installed with CUDA support, as it is needed for GPU usage (uninstalling and re-installing in accordance with needed CUDA version)
# [NOTE] Officially, it supports CUDA 11.8 and 12.1
gpu_not_available = False

try:
    import torch
    print("PyTorch version:", torch.__version__)
    # Verify GPU accessibility
    if torch.cuda.is_available():
        print(f"GPU Detected: {torch.cuda.get_device_name(0)}")
    else:
        print("WARNING: No GPU detected. Training will be extremely slow or fail.")
        gpu_not_available = True
except (ImportError, OSError):
    print("PyTorch is not installed or there is an error importing it.")

Environment: Colab | OS: Linux
PyTorch version: 2.10.0+cu128
GPU Detected: Tesla T4

### 0.1. PyTorch and CUDA checks

The following cell is designed to *force* some legacy libraries to work together. As of 2026 this might not be necessary, so a check was set in place to skip the *re-installation* if it was deemed not needed.

#### *If the user is attempting to run the code on Windows...*

It is important that the user previously downloads the appropriate CUDA Toolkit so that the program may find it (DLL problems down the line, if not). The version used by the second developer, could be found through this link: `https://developer.nvidia.com/cuda-12-8-0-download-archive?target_os=Windows` (*selected Windows, x86, 11, exe local*)

If there was a **CUDA-INCOMPATIBLE PYTORCH PREVIOUSLY IMPORTED** (that is, if previous or following cell were executed and the last check came back *False*) restart kernel: `Ctrl+Shift+P -> Jupyter: Restart Kernel` before executing this cell to avoid crashes or file locks.

If **uninstallation of PyTorch** from within fails, attempt to do so from a terminal (it might be faster): `pip uninstall torch torchvision torchaudio`

To see exactly which CUDA version the user's hardware can support (assuming they have an NVIDIA GPU), type in a terminal: `nvidia-smi`

In [24]:
import subprocess, platform, sys, os

try:
    if gpu_not_available:
        if IS_COLAB:
            print("In Colab, PyTorch with CUDA is pre-installed.")
            print("If no GPU is detected, go to: Runtime > Change runtime type > T4 GPU.")
        else:
            # Local Windows: reinstall PyTorch for the installed CUDA version
            torch_version = "2.7.1"
            torchvision_version = "0.22.1"
            torchaudio_version = "2.7.1"
            cuda_version = "cu128"  # Match your local CUDA (second developer: 12.8)
            index_url = f"https://download.pytorch.org/whl/{cuda_version}"
            print("Uninstalling existing torch packages (if any)...")
            subprocess.call([sys.executable, "-m", "pip", "uninstall", "-y",
                             "torch", "torchvision", "torchaudio"])
            print(f"Installing PyTorch {torch_version} with CUDA {cuda_version}...")
            subprocess.check_call([
                sys.executable, "-m", "pip", "install",
                f"torch=={torch_version}",
                f"torchvision=={torchvision_version}",
                f"torchaudio=={torchaudio_version}",
                "--index-url", index_url
            ])
except NameError:
    print("WARNING: Run cell 6 first to initialise IS_COLAB / gpu_not_available.")

**DO NOT RUN** the following cell if not responding to the **Breaking Point** from cell **2.1**.

In [25]:
import subprocess, sys

# Unsloth/vLLM local install (Colab is handled in Section 1 below)
if not IS_COLAB:
    subprocess.check_call([
        sys.executable, "-m", "pip", "install",
        "--quiet", "--upgrade", "--no-deps",
        "unsloth", "unsloth_zoo", "trl<0.15.0"
    ])

### 0.2. Check for GPU detection

To re-check that the libraries are playing nice to each other now that some maneuvering has been done.

In [26]:
import torch
print("PyTorch version:", torch.__version__)
if torch.cuda.is_available():
    print("CUDA Detected:", torch.cuda.get_device_name(0)) # Should show user's GPU

PyTorch version: 2.10.0+cu128
CUDA Detected: Tesla T4

## 1. Installation

### 1.1. Unsloth and vLLM installation

Again, this might not be needed as of 2026. So, it may be skipped.

*If it is not skipped*, and if the **local environment** is being executed within **WINDOWS**, *Microsoft Visual C++ Build Tools* are necessary for the Unsloth installation to succeed, as it needs to compile specific kernels during the install. Also *vLLM* is, as of 2025-2026, still **not compatible** with Windows and, as such, is skipped in this case.

In [27]:
import subprocess, sys, os

if IS_COLAB:
    print("Installing Unsloth and required backends...")

    # Unsloth 2026 requires the following specific support libraries
    deps = [
        "unsloth",
        "unsloth_zoo>=2026.5.1",
        "hf_transfer",
        "tyro",
        "bitsandbytes>=0.45.5,!=0.46.0,!=0.48.0",
        "xformers>=0.0.27.post2"
    ]
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q"] + deps)

    # Enable fast HuggingFace downloads (if needed)
    os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"
    print("Colab Unsloth install complete.")
else:
    print("Local environment: skipping Colab-specific installs.")

Installing Unsloth and required backends...
Colab Unsloth install complete.

### 1.2. Installation of needed libraries

If the user is using a **local environment**, *restart the kernel* to ensure all installations are correctly applied: `Ctrl+Shift+P -> Jupyter: Restart Kernel`

Then, the user might need to **re-run** cells **0.1**, **0.2** and **1.1** to ensure the GPU and the previously downloadad libraries are correctly detected after the restart.

In [66]:
import subprocess, sys

easy_installation_ran = True

# We pin versions that satisfy Unsloth 2026 and LangChain
deps = [
    "huggingface_hub>=0.34.0",      # Required by Unsloth and Gradio
    "transformers==5.5.0",          # Unsloth 2026 forbids 5.0.0
    "datasets>=4.2.0,<4.4.0",       # Unsloth 2026 forbids 4.0.x/4.1.x
    "trl<0.15.0",                   # Maximum compatible version for Unsloth
    "peft>=0.13.0",                 # Compatible with transformers 5.x (0.5.0 was 2022 era)
    "accelerate>=0.34.0",
    "langchain-core",
    "langchain-google-genai",
    "langchain-huggingface>=0.1.0"
]

try:
    print("Upgrading pip...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "--upgrade", "pip"])
    print("Pip upgraded successfully.")

    print(f"Installing dependencies for {'Google Colab' if IS_COLAB else 'local environment'}...")
    for dep in deps:
        print(f"Attempting to install: {dep}")
        subprocess.check_call([sys.executable, "-m", "pip", "install", dep])
    print("All dependencies installed successfully.")
except subprocess.CalledProcessError as e:
    print(f"WARNING: Dependency install failed for one or more packages: {e}")
    easy_installation_ran = False

Upgrading pip...
Pip upgraded successfully.
Installing dependencies for Google Colab...
Attempting to install: huggingface_hub>=0.34.0
Attempting to install: transformers==5.5.0
Attempting to install: datasets>=4.2.0,<4.4.0
Attempting to install: trl<0.15.0
Attempting to install: peft==0.5.0
Attempting to install: accelerate
Attempting to install: langchain-core
Attempting to install: langchain-google-genai
Attempting to install: langchain-huggingface
All dependencies installed successfully.

In [29]:
import importlib, subprocess, sys

optional_backends = {
    "langchain_openai":    "langchain-openai",
    "langchain_anthropic": "langchain-anthropic",
    "langchain_ollama":    "langchain-ollama",
    "langchain_community": "langchain-community"
}

for module, package in optional_backends.items():
    try:
        importlib.import_module(module)
    except ImportError:
        print(f"Installing optional backend: {package}...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])

print("Optional LangChain backends ready.")

Optional LangChain backends ready.

## 2. Imports

### 2.1. Breaking Point (2025-2026)

*If the user is attempting to run the code on Windows...*

It may happen that Usloth or TRL de-synch the Torch and Torchvision versions (which were specified in **0.2**), often because they forced an update to one but not the other. This results in errors such as `Exception: partially initialized module 'torchvision' has no attribute 'extension' (most likely due to a circular import)`, or an error loading a Torch file which the computer is clearly able to find. On **WINDOWS**, this is compounded by the fact that Torchvision expects a specific compiled C++ extension that isn't finding its matching Torch base. This is, in short, a case of *circular dependency* between both libraries. To fix this, re-run **0.1** (both cells) to *force* their re-synchronisation. Then, re-run **0.2** to make sure the GPU is correctly detected.

After executing these cells, the user must **immediatelly restart the kernel**: `Ctrl+Shift+P -> Jupyter: Restart Kernel`

Finally, re-run cell **2** to import the necessary libraries to build the model.

### 2.2. Dynamic-Link Library (DLL) in Windows

A persistent error the user might find is the program's failure to initialise the Dynamic-Link Library, or DLL. This might be fixed by manually adding to their DLL directory the path to the CUDA version in use as a new variable. The user may open a terminal and input the following command: `$env:Path = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.8\bin;" + $env:Path` (where `v12.8` must be changed to the user's used CUDA version; the path is in quotations because it contains spaces).

### 2.3. NumPy Library

After all, a new error might appear, claiming that `A module that was compiled using NumPy 1.x cannot be run in NumPy 2.2.6 as it may crash.` This asks for the user to re-run cell **1.2**. Hopefully, this will be the last of the errors and safe passage to the actual module tinkering stage of the project may be granted after this.

### 2.4. Round and round and round we go

The user might find themselves seemingly going in circles, iterating over and over again on the three aforementioned errors. To escape such a Sisyphus-like merry-go-round of circular Torch/Torchvision desynchronization, DLL failures, and NumPy version conflicts, the user might have to call it quits and go back to **Google Colab** to run this code.

In [30]:
import os, re, math, time, json
import platform
import logging
import numpy as np
import pandas as pd
from tqdm import tqdm
from typing import Optional, Union

# Suppress torchao's version-mismatch log -- torch 2.10 is below torchao's 2.11+ floor for
# its cpp extensions, but this does not prevent training from working on Colab T4.
logging.getLogger("torchao").setLevel(logging.ERROR)

# Compatibility
if IS_WINDOWS:
    os.environ["UNSLOTH_IS_WINDOWS"] = "1" # Inform Unsloth about Windows environment (if Usloth is being used)

_use_standard_stack = globals().get("easy_installation_ran", True)

try:
    if _use_standard_stack:
        # Standard AI Stack (alternative to FastLanguageModel)
        import torch
        from datasets import Dataset
        from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
        from peft import LoraConfig, get_peft_model
        from trl import SFTTrainer, SFTConfig, GRPOTrainer, GRPOConfig

    else:
        # Import Unsloth before anything else AI-related to avoid conflicts
        from unsloth import FastLanguageModel

        # Transformers-dependent imports
        from datasets import Dataset
        from trl import SFTTrainer, SFTConfig, GRPOTrainer, GRPOConfig

        # LangChain imports
        from langchain_core.language_models import BaseLanguageModel, BaseChatModel # New path (2025-2026)
        from langchain_core.prompts import ChatPromptTemplate

except ImportError as e:
    print(f"WARNING: Import failed -- {e}.")
    print("Re-run cell 1.2 (to install updated packages) then restart the runtime.")
except Exception as e:
    print(f"WARNING: Unexpected error during imports -- {type(e).__name__}: {e}.")
    print("Re-run cells 0.1 and 1.2, then restart the runtime.")

## 3. Loading the model

*If this is an Unsloth run*, the user might have had to **restart the runtime** (*Google Colab*) or **restart the kernel** (*venv*). To load the model, cells **0.1**, **1.1** and **1.2** might have to be *re-run* so that PyTorch, vLLM and the other needed libraries are installed and compatible and the GPU knows it.

In [31]:
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model
import torch

max_seq_length = 2048   # Reduce to 1024 if you hit OOM during generation
lora_rank = 16          # 16 is a good T4 balance (was 32, halved for memory)

is_unsloth_available = False
try:
    from unsloth import FastLanguageModel
    is_unsloth_available = True
except ImportError:
    pass

if is_unsloth_available:
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "unsloth/Qwen3-4B-Base",
        max_seq_length = max_seq_length,
        load_in_4bit = True,            # Essential for T4 (15 GB VRAM)
        fast_inference = False,         # Keep False: vLLM requires specific CUDA on T4
        max_lora_rank = lora_rank,
        gpu_memory_utilization = 0.45,  # Conservative: leaves room for activations
    )

    model = FastLanguageModel.get_peft_model(
        model,
        r = lora_rank,
        target_modules = [
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj",
        ],
        lora_alpha = lora_rank * 2,
        use_gradient_checkpointing = "unsloth",
        random_state = 3407,
    )
    print("Model loaded via Unsloth (4-bit + LoRA).")

else:
    MODEL_ID = "Qwen/Qwen3-4B"  # Same architecture as the Unsloth path

    bnb_config = BitsAndBytesConfig(
        load_in_4bit = True,
        bnb_4bit_quant_type = "nf4",
        bnb_4bit_compute_dtype = torch.float16,
        bnb_4bit_use_double_quant = True,
    )

    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        quantization_config = bnb_config,
        device_map = "auto",
        trust_remote_code = True,
    )
    model.config.use_cache = False
    model.gradient_checkpointing_enable()

    lora_config = LoraConfig(
        r = lora_rank,
        lora_alpha = lora_rank * 2,
        target_modules = [
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj",
        ],
        bias = "none",
        task_type = "CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    print("Model loaded via HuggingFace transformers (4-bit + LoRA).")

model.print_trainable_parameters()

==((====))==  Unsloth 2026.5.2: Fast Qwen3 patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

unsloth/qwen3-4b-base-unsloth-bnb-4bit does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.
Model loaded via Unsloth (4-bit + LoRA).
trainable params: 33,030,144 || all params: 4,055,498,240 || trainable%: 0.8145

## 4. Setting up the template

It is time to start setting up the model's responses to user input.

In [32]:
reasoning_start = "<think>"   # Acts as <think>
reasoning_end   = "</think>"  # Acts as </think>
solution_start  = "<O>"
solution_end    = "</O>"

system_prompt =   f"""You are a helpful assistant.
You are given a dilemma. You must decide if the author is acting correctly according to moral reasoning.
You must consider these moral axioms, from top priority (1) to least (10):
1.	To not kill innocent people.
2.	To not cause unnecessary harm nor suffering.
3.	To not deceive nor steal.
4.	To comply with promises and honour one's agreements.
5.	To not deprive anyone from freedom.
6.	To act justly.
7.	To be truthful.
8.	To help others.
9.	To be grateful.
10.	To obey positive laws that are just.
You must accommodate as many axioms as possible. Answer 'No: ' and the numbers of the unapliccable axioms.
Decide if the author is acting correctly in this moral reasoning in 100 characters or less.
Place your answer between {reasoning_start} and {reasoning_end}.
Then answer "RIGHT" or "WRONG" within {solution_start} and {solution_end} as the final verdict.
"""
system_prompt

'You are a helpful assistant.\nYou are given a dilemma. You must decide if the author is acting correctly according to moral reasoning.\nYou must consider these moral axioms, from top priority (1) to least (10):\n1.\tTo not kill innocent people.\n2.\tTo not cause unnecessary harm nor suffering.\n3.\tTo not deceive nor steal.\n4.\tTo comply with promises and honour one\'s agreements.\n5.\tTo not deprive anyone from freedom.\n6.\tTo act justly.\n7.\tTo be truthful.\n8.\tTo help others.\n9.\tTo be grateful.\n10.\tTo obey positive laws that are just.\nYou must accommodate as many axioms as possible. Answer \'No: \' and the numbers of the unapliccable axioms.\nDecide if the author is acting correctly in this moral reasoning in 100 characters or less.\nPlace your answer between <think> and </think>.\nThen answer "RIGHT" or "WRONG" within <O> and </O> as the final verdict.\n'

Large Language Models (LLMs) do **not** understand a list of `user` and `assistant` messages. Not directly, at least. They need the _conversation_ to be formatted into a specific `string` structure, often including special tokens to delineate roles and turns. For this, we create `chat_template`.

In [33]:
# "chat_template" defines how the model will process conversations, including user inputs and assistant responses.

chat_template = """{% if messages[0]['role'] == 'system' %}
{{ messages[0]['content'] + eos_token }}
{% set loop_messages = messages[1:] %}
{% else %}
{{ '{system_prompt}' + eos_token }}
{% set loop_messages = messages %}
{% endif %}
{% for message in loop_messages %}
{% if message['role'] == 'user' %}
{{ message['content'] }}
{% elif message['role'] == 'assistant' %}
{{ message['content'] + eos_token }}
{% endif %}
{% endfor %}
{% if add_generation_prompt %}{{ '{reasoning_start}' }}
{% endif %}"""

tokenizer.chat_template = chat_template

# Note "system_prompt" and "reasoning_start", which was defined in the previous cell.

For each list in the application of  `chat_template`:

* The `role` entry in the dictionary corresponds to the assignation of a message within the _conversation history_. It may be `user` or `assistant`.

* The `content` entry in the dictionary corresponds to the content of a message within the _conversation history_, each assigned to a `role`.

In the following cell, an *example* for a _conversation history_ (completely fabricated) has been written. It may be noted that the `user` interactions have a simpler syntax in their `content`, while the `assistant` calls upon variables which were initialised when drawing up `system_prompt`.

*  This helps illustrate the  difference between `reasoning_x` (enclosing _I think it's 2_) and `solution_x` (enclosing _2_) (`x` corresponding to either `start` or `end`), which are custom tokens embedded within the `assistant`'s `content`. They help structure the model's output for specific tasks.

Then, two arguments are included:

* `tokenize = False` specifies that the output should be a plain `string`, not a list of numerical token IDs. If it was `True`, it would convert the output to said list.

* `add_generation_prompt = True` makes sure the tokenizer adds a special prompt or token at the end of the formatted `string`. This signals that it is now the model's turn to generate a response, rather than waiting for further input.

In [34]:
tokenizer.apply_chat_template([
    {"role" : "user", "content" : "What is 1+1?"},
    {"role" : "assistant", "content" : f"{reasoning_start}I think it's 2.{reasoning_end}{solution_start}2{solution_end}"},
    {"role" : "user", "content" : "What is 2+2?"},
], tokenize = False, add_generation_prompt = True)

"{system_prompt}<|endoftext|>\nWhat is 1+1?\n<think>I think it's 2.</think><O>2</O><|endoftext|>\nWhat is 2+2?\n{reasoning_start}\n"

## 5. Loading the data

In [35]:
def filter_by_title(df, title_query, case_sensitive=False):
    """
    Filter the DataFrame to find entries with titles containing the specified query

    Parameters:
    -----------
    df : pandas.DataFrame
        The DataFrame to search
    title_query : str
        The title text to search for
    case_sensitive : bool, default=False
        Whether to perform a case-sensitive search

    Returns:
    --------
    pandas.DataFrame
        DataFrame containing rows with matching titles
    """
    if case_sensitive:
        matching_rows = df[df['title'].str.contains(title_query, na=False)]
    else:
        matching_rows = df[df['title'].str.contains(title_query, case=False, na=False)]

    return matching_rows

def get_exact_title_match(df, title):
    """
    Get the exact row that matches the complete title

    Parameters:
    -----------
    df : pandas.DataFrame
        The DataFrame to search
    title : str
        The exact title to match

    Returns:
    --------
    pandas.Series or None
        The matching row or None if no match found
    """
    matching_rows = df[df['title'] == title]

    if len(matching_rows) == 1:
        return matching_rows.iloc[0]
    elif len(matching_rows) > 1:
        print(f"Warning: Multiple matches found for title '{title}'")
        return None
    else:
        print(f"No exact match found for title '{title}'")
        return None

### 5.1. Where can I find my dataset?

The following cell is prepared to find the dataset at the core of this project (_Am I The Asshole?_, a Reddit board) someplace in the user's Google Drive. Ignoring the commented code lines, which intend on showing the user their current directory and what is stored there, these instructions make sure the user can access their Google Drive folders easily, from the [default unit](https://drive.google.com/drive/u/0/my-drive):

```
current_path = current_path = os.getcwd()
current_path = os.path.join(current_path, "drive", "MyDrive")
```

Then, `scores_path` and `reasoning_path` serves as a concatenation of the steps the project will have to take in order to reach the datasets for this project: `reasoning_socres.csv` and `reasoning_dataset.csv`. **The user will need to alter these steps to match the exact location of the CSV files within their Google Drive**.

In [36]:
import os
from google.colab import drive

if "COLAB_" in "".join(os.environ.keys()):
  drive.mount('/content/drive')

  current_path = os.getcwd()
  # current_dir_content = os.listdir(current_path)
  # print(f"Current working directory: {current_path}")
  # print(f"Contents of current working directory: {current_dir_content}")
  current_path = os.path.join(current_path, "drive", "MyDrive")

  # Each listed entry is a step in the path towards the desired file (at the end of the list)
  # The user may change it to match their own path
  scores_path = os.path.join(current_path, "Universitat", "UB - Filosofia", "Pràctiques", "Reasoning Datasets", "reasoning_scores.csv")
  reasoning_path = os.path.join(current_path, "Universitat", "UB - Filosofia", "Pràctiques", "Reasoning Datasets", "reasoning_dataset.csv")

  scores_df = pd.read_csv(scores_path)
  reasoning_df = pd.read_csv(reasoning_path)

Mounted at /content/drive

In [37]:
scores_df.head()

,title,NEUTRALITY,EVIDENCE_INTEGRATION,HYPOTHESIS_TESTING,LOGICAL_COHERENCE,NUANCE_RECOGNITION,DECISION_ALIGNMENT,TOTAL_SCORE,COGNITIVE_QUALITY_RATING,SUMMARY_DIAGNOSIS,target_decision
0,AITA for not wanting to have any contact with ...,8,7,8,7,8,9,47,FUNCTIONAL_REASONING,The reasoning demonstrates functional quality ...,RIGHT
1,AITA for telling my three best friends that th...,8,7,8,7,9,8,47,FUNCTIONAL_REASONING,The reasoning demonstrates functional quality ...,RIGHT
2,AITA for thinking showing pubes in public is a...,8,7,8,7,9,8,47,FUNCTIONAL_REASONING,The reasoning demonstrates functional analytic...,RIGHT
3,AITA for refusing to accept mental illness as ...,7,8,7,8,8,9,47,FUNCTIONAL_REASONING,The reasoning demonstrates functional analytic...,RIGHT
4,WIBTA if I told my husband we REALLY need to c...,8,7,8,7,9,8,47,FUNCTIONAL_REASONING,The reasoning demonstrates functional quality ...,RIGHT

In [38]:
titles = scores_df["title"]

In [39]:
stories = list()
reasonings = list()
target = list()
titles_complete  = list()

for title in titles:
    column = get_exact_title_match(reasoning_df, title)
    if column is None:
        continue

    text = column["text"]
    output = column["output"]
    reasoning = column["initial_analysis"] + column["dialectical_challenge"] + column["integration"] + f"\n Therefore the author is doing the { output } thing."


    stories.append(text)
    reasonings.append(reasoning)
    target.append(output)
    titles_complete.append(title)

len(stories), len(reasonings), len(target), len(titles_complete)

Warning: Multiple matches found for title 'AITA'

(2477, 2477, 2477, 2477)

### 5.2. Structuring the data

Now, we have to format the dataset to follow our **GRPO** (Generative Reinforcement Learning with Policy Optimisation) style formatting, which involves **structuring each data entry** into a specific conversational format that the LLM can understand.

In [40]:
dataset = pd.DataFrame({
    'expected_answer': target,
    'problem': stories,
    'generated_solution': reasonings,
    'title': titles_complete
})

In [41]:
def format_dataset(x):
    expected_answer = x["expected_answer"]
    problem = x["problem"]

    # Remove generated <think> and </think>
    thoughts = x["generated_solution"]
    thoughts = thoughts.replace("<think>", "").replace("</think>", "")

    # Strip newlines on left and right
    thoughts = thoughts.strip()
    # Add our custom formatting
    final_prompt = \
        reasoning_start + thoughts + reasoning_end + \
        solution_start + expected_answer + solution_end
    return [
        {"role" : "system",    "content" : system_prompt},
        {"role" : "user",      "content" : problem},
        {"role" : "assistant", "content" : final_prompt},
    ]

## 6. SFT Training

### 6.1. Dataset Setup

In [42]:
sft_dataset = dataset.copy()

sft_dataset = sft_dataset[:100]

sft_dataset = sft_dataset.copy()  # avoid SettingWithCopyWarning
sft_dataset["Messages"] = sft_dataset.apply(format_dataset, axis=1)

Make sure the setup worked correctly by running the following cell. This should output:

1. The original `system_prompt`.

2. The `eos_token` (*eos* means *End of Sentence*) immediately following the system prompt.

3. The `content` of the `user`'s message, which is the problem statement from `sft_dataset["Messages"][0]` (that is, row `0` from the `Messages` column in `sft_dataset`, the structured dataset).

4. The `content` of the `assistance`'s response, which starts with `reasoning_start` immediatelly afterwards. Then, the generated solution is provided, followed by `reasoning_end`. Finally, the expected answer is provided between `solution_start` and `solution_end`.

5. A second `eos_token` (End of Sentence).

6. _(Because of `add_generation_prompt = True` in the second code cell in **4**)_ A final `reasoning_start` to signal that the model should now generate its response.

In [43]:
tokenizer.apply_chat_template(sft_dataset["Messages"][0], tokenize = False)

'You are a helpful assistant.\nYou are given a dilemma. You must decide if the author is acting correctly according to moral reasoning.\nYou must consider these moral axioms, from top priority (1) to least (10):\n1.\tTo not kill innocent people.\n2.\tTo not cause unnecessary harm nor suffering.\n3.\tTo not deceive nor steal.\n4.\tTo comply with promises and honour one\'s agreements.\n5.\tTo not deprive anyone from freedom.\n6.\tTo act justly.\n7.\tTo be truthful.\n8.\tTo help others.\n9.\tTo be grateful.\n10.\tTo obey positive laws that are just.\nYou must accommodate as many axioms as possible. Answer \'No: \' and the numbers of the unapliccable axioms.\nDecide if the author is acting correctly in this moral reasoning in 100 characters or less.\nPlace your answer between <think> and </think>.\nThen answer "RIGHT" or "WRONG" within <O> and </O> as the final verdict.\n<|endoftext|>\nSo my father used to mentally and physically abuse me for a very long time, from like my 10th till I moved out (19). And now he claims that he wants to have contact again but I don\'t want it anymore. He didn\'t even tell me he is sorry for the things he did. Now everyone says I\'m the asshole because he wants to \'make things right\' but I don\'t give him the chance., am I the asshole here?\n\n&amp;#x200B;\n\np.s. excuse me for my English \n<think>The situation involves a complex history of abuse and the current desire of the father to reconnect. \n\n1. **Hypothesis 1: The father genuinely wants to make amends.**\n   - Evidence for: He has expressed a desire to reconnect, which could indicate a change of heart.\n   - Evidence against: He has not apologized or acknowledged the harm he caused, which raises doubts about his sincerity.\n\n2. **Hypothesis 2: The father is seeking to alleviate his own guilt.**\n   - Evidence for: His lack of an apology suggests he may be more focused on his own feelings than on the victim\'s needs.\n   - Evidence against: He may genuinely believe that reconnecting is a way to make things right, despite not expressing remorse.\n\n3. **Hypothesis 3: The individual has a right to refuse contact based on past trauma.**\n   - Evidence for: The history of abuse justifies the individual\'s decision to prioritize their mental health and well-being.\n   - Evidence against: Some may argue that forgiveness is important for healing, and that the individual should at least consider the father\'s request.\n\nThe most diagnostic evidence lies in the father\'s lack of an apology, which strongly suggests that his motivations may not be entirely altruistic. The individual’s feelings of discomfort and refusal to engage are valid responses to a history of trauma.While the individual\'s refusal to reconnect is understandable, one could argue that the father\'s desire to make amends, even if not perfectly executed, should be considered. Some might view the refusal as a missed opportunity for healing and reconciliation. Additionally, societal norms often emphasize forgiveness and the potential for change in relationships. However, it is crucial to recognize that reconciliation should not come at the expense of the individual\'s mental health and safety. The absence of an apology from the father indicates a lack of accountability, which is a significant barrier to any potential reconciliation.The analysis reveals that while there are arguments for considering the father\'s desire to reconnect, the lack of an apology and acknowledgment of past abuse fundamentally undermines his position. The individual\'s right to refuse contact is rooted in self-preservation and the need to prioritize their mental health. Ethical frameworks that emphasize autonomy and the importance of consent support the conclusion that the individual is not an "asshole" for wanting to maintain distance from an abusive parent. Ultimately, the decision to refuse contact is reasonable given the context of past trauma and the father\'s failure to take responsibility for his actions.\n Therefore the author is doing the RIGHT thing.</think><O>RIGHT</O><|endoftext|>\n'

To **avoid exceedingly long reasoning traces**, the pre-fine-tuning dataset is **truncated** to `max_seq_length/2`.

In [44]:
sft_dataset["N"] = sft_dataset["Messages"].apply(lambda x: len(tokenizer.apply_chat_template(x)))

sft_dataset = sft_dataset.loc[sft_dataset["N"] <= max_seq_length/2].copy()
sft_dataset.shape

(15, 6)

Then, the messages are **tokenised** and converted into a *Hugging Face*-compatible dataset format.

In [45]:
sft_dataset["text"] = tokenizer.apply_chat_template(sft_dataset["Messages"].values.tolist(), tokenize = False)
sft_dataset = Dataset.from_pandas(sft_dataset[["text"]])
sft_dataset

Dataset({
    features: ['expected_answer', 'problem', 'generated_solution', 'title', 'Messages', 'N', 'text', '__index_level_0__'],
    num_rows: 15
})

The **tokenisation** includes:

* `expected_answer`: The annotated "correct" answer included in the provided dataset. This will be instrumental in evaluating the model's accuracy in its moral reasoning, as it is the _Gold Standard_ to which its output will be compared.

* `problem`: The situation or moral dilemma presented to the model to provide a moral solution.

* `generated_solution`: The moral reasoning the model outputs when confronted with the situation described in `problem`.

* `title`: The title attached to the situation or moral dilemma, as provided by its author. It can serve as a summary of the main problem at hand.

* `Messages`: The transcript of the tokenised conversation between the `user` and the `assistant`, from the `system_prompt` to the `generated_solution`.

* `N`: The amount of entries of the dataset which have not been filtered out by the `max_seq_length/2` as the maximum length of `Messages`.

* `text`: The transcript of the conversation, from the `system_prompt` to the `generated_solution`, without tokenising each message's `content` within a dictionary which specifies the `role` it would be assigned to. Rather, it shows the syntax as specified in `system_prompt`.

In [46]:
sft_dataset[0]

{'expected_answer': 'RIGHT',
 'problem': "So my father used to mentally and physically abuse me for a very long time, from like my 10th till I moved out (19). And now he claims that he wants to have contact again but I don't want it anymore. He didn't even tell me he is sorry for the things he did. Now everyone says I'm the asshole because he wants to 'make things right' but I don't give him the chance., am I the asshole here?\n\n&amp;#x200B;\n\np.s. excuse me for my English ",
 'generated_solution': 'The situation involves a complex history of abuse and the current desire of the father to reconnect. \n\n1. **Hypothesis 1: The father genuinely wants to make amends.**\n   - Evidence for: He has expressed a desire to reconnect, which could indicate a change of heart.\n   - Evidence against: He has not apologized or acknowledged the harm he caused, which raises doubts about his sincerity.\n\n2. **Hypothesis 2: The father is seeking to alleviate his own guilt.**\n   - Evidence for: His lack of an apology suggests he may be more focused on his own feelings than on the victim\'s needs.\n   - Evidence against: He may genuinely believe that reconnecting is a way to make things right, despite not expressing remorse.\n\n3. **Hypothesis 3: The individual has a right to refuse contact based on past trauma.**\n   - Evidence for: The history of abuse justifies the individual\'s decision to prioritize their mental health and well-being.\n   - Evidence against: Some may argue that forgiveness is important for healing, and that the individual should at least consider the father\'s request.\n\nThe most diagnostic evidence lies in the father\'s lack of an apology, which strongly suggests that his motivations may not be entirely altruistic. The individual’s feelings of discomfort and refusal to engage are valid responses to a history of trauma.While the individual\'s refusal to reconnect is understandable, one could argue that the father\'s desire to make amends, even if not perfectly executed, should be considered. Some might view the refusal as a missed opportunity for healing and reconciliation. Additionally, societal norms often emphasize forgiveness and the potential for change in relationships. However, it is crucial to recognize that reconciliation should not come at the expense of the individual\'s mental health and safety. The absence of an apology from the father indicates a lack of accountability, which is a significant barrier to any potential reconciliation.The analysis reveals that while there are arguments for considering the father\'s desire to reconnect, the lack of an apology and acknowledgment of past abuse fundamentally undermines his position. The individual\'s right to refuse contact is rooted in self-preservation and the need to prioritize their mental health. Ethical frameworks that emphasize autonomy and the importance of consent support the conclusion that the individual is not an "asshole" for wanting to maintain distance from an abusive parent. Ultimately, the decision to refuse contact is reasonable given the context of past trauma and the father\'s failure to take responsibility for his actions.\n Therefore the author is doing the RIGHT thing.',
 'title': 'AITA for not wanting to have any contact with my father?',
 'Messages': [{'role': 'system',
   'content': 'You are a helpful assistant.\nYou are given a dilemma. You must decide if the author is acting correctly according to moral reasoning.\nYou must consider these moral axioms, from top priority (1) to least (10):\n1.\tTo not kill innocent people.\n2.\tTo not cause unnecessary harm nor suffering.\n3.\tTo not deceive nor steal.\n4.\tTo comply with promises and honour one\'s agreements.\n5.\tTo not deprive anyone from freedom.\n6.\tTo act justly.\n7.\tTo be truthful.\n8.\tTo help others.\n9.\tTo be grateful.\n10.\tTo obey positive laws that are just.\nYou must accommodate as many axioms as possible. Answer \'No: \' and the numbers of the unapliccable axioms.\nDecide if the author is acting correctly in this moral reasoning in 100 characters or less.\nPlace your answer between <think> and </think>.\nThen answer "RIGHT" or "WRONG" within <O> and </O> as the final verdict.\n'},
  {'role': 'user',
   'content': "So my father used to mentally and physically abuse me for a very long time, from like my 10th till I moved out (19). And now he claims that he wants to have contact again but I don't want it anymore. He didn't even tell me he is sorry for the things he did. Now everyone says I'm the asshole because he wants to 'make things right' but I don't give him the chance., am I the asshole here?\n\n&amp;#x200B;\n\np.s. excuse me for my English "},
  {'role': 'assistant',
   'content': '<think>The situation involves a complex history of abuse and the current desire of the father to reconnect. \n\n1. **Hypothesis 1: The father genuinely wants to make amends.**\n   - Evidence for: He has expressed a desire to reconnect, which could indicate a change of heart.\n   - Evidence against: He has not apologized or acknowledged the harm he caused, which raises doubts about his sincerity.\n\n2. **Hypothesis 2: The father is seeking to alleviate his own guilt.**\n   - Evidence for: His lack of an apology suggests he may be more focused on his own feelings than on the victim\'s needs.\n   - Evidence against: He may genuinely believe that reconnecting is a way to make things right, despite not expressing remorse.\n\n3. **Hypothesis 3: The individual has a right to refuse contact based on past trauma.**\n   - Evidence for: The history of abuse justifies the individual\'s decision to prioritize their mental health and well-being.\n   - Evidence against: Some may argue that forgiveness is important for healing, and that the individual should at least consider the father\'s request.\n\nThe most diagnostic evidence lies in the father\'s lack of an apology, which strongly suggests that his motivations may not be entirely altruistic. The individual’s feelings of discomfort and refusal to engage are valid responses to a history of trauma.While the individual\'s refusal to reconnect is understandable, one could argue that the father\'s desire to make amends, even if not perfectly executed, should be considered. Some might view the refusal as a missed opportunity for healing and reconciliation. Additionally, societal norms often emphasize forgiveness and the potential for change in relationships. However, it is crucial to recognize that reconciliation should not come at the expense of the individual\'s mental health and safety. The absence of an apology from the father indicates a lack of accountability, which is a significant barrier to any potential reconciliation.The analysis reveals that while there are arguments for considering the father\'s desire to reconnect, the lack of an apology and acknowledgment of past abuse fundamentally undermines his position. The individual\'s right to refuse contact is rooted in self-preservation and the need to prioritize their mental health. Ethical frameworks that emphasize autonomy and the importance of consent support the conclusion that the individual is not an "asshole" for wanting to maintain distance from an abusive parent. Ultimately, the decision to refuse contact is reasonable given the context of past trauma and the father\'s failure to take responsibility for his actions.\n Therefore the author is doing the RIGHT thing.</think><O>RIGHT</O>'}],
 'N': 855,
 'text': 'You are a helpful assistant.\nYou are given a dilemma. You must decide if the author is acting correctly according to moral reasoning.\nYou must consider these moral axioms, from top priority (1) to least (10):\n1.\tTo not kill innocent people.\n2.\tTo not cause unnecessary harm nor suffering.\n3.\tTo not deceive nor steal.\n4.\tTo comply with promises and honour one\'s agreements.\n5.\tTo not deprive anyone from freedom.\n6.\tTo act justly.\n7.\tTo be truthful.\n8.\tTo help others.\n9.\tTo be grateful.\n10.\tTo obey positive laws that are just.\nYou must accommodate as many axioms as possible. Answer \'No: \' and the numbers of the unapliccable axioms.\nDecide if the author is acting correctly in this moral reasoning in 100 characters or less.\nPlace your answer between <think> and </think>.\nThen answer "RIGHT" or "WRONG" within <O> and </O> as the final verdict.\n<|endoftext|>\nSo my father used to mentally and physically abuse me for a very long time, from like my 10th till I moved out (19). And now he claims that he wants to have contact again but I don\'t want it anymore. He didn\'t even tell me he is sorry for the things he did. Now everyone says I\'m the asshole because he wants to \'make things right\' but I don\'t give him the chance., am I the asshole here?\n\n&amp;#x200B;\n\np.s. excuse me for my English \n<think>The situation involves a complex history of abuse and the current desire of the father to reconnect. \n\n1. **Hypothesis 1: The father genuinely wants to make amends.**\n   - Evidence for: He has expressed a desire to reconnect, which could indicate a change of heart.\n   - Evidence against: He has not apologized or acknowledged the harm he caused, which raises doubts about his sincerity.\n\n2. **Hypothesis 2: The father is seeking to alleviate his own guilt.**\n   - Evidence for: His lack of an apology suggests he may be more focused on his own feelings than on the victim\'s needs.\n   - Evidence against: He may genuinely believe that reconnecting is a way to make things right, despite not expressing remorse.\n\n3. **Hypothesis 3: The individual has a right to refuse contact based on past trauma.**\n   - Evidence for: The history of abuse justifies the individual\'s decision to prioritize their mental health and well-being.\n   - Evidence against: Some may argue that forgiveness is important for healing, and that the individual should at least consider the father\'s request.\n\nThe most diagnostic evidence lies in the father\'s lack of an apology, which strongly suggests that his motivations may not be entirely altruistic. The individual’s feelings of discomfort and refusal to engage are valid responses to a history of trauma.While the individual\'s refusal to reconnect is understandable, one could argue that the father\'s desire to make amends, even if not perfectly executed, should be considered. Some might view the refusal as a missed opportunity for healing and reconciliation. Additionally, societal norms often emphasize forgiveness and the potential for change in relationships. However, it is crucial to recognize that reconciliation should not come at the expense of the individual\'s mental health and safety. The absence of an apology from the father indicates a lack of accountability, which is a significant barrier to any potential reconciliation.The analysis reveals that while there are arguments for considering the father\'s desire to reconnect, the lack of an apology and acknowledgment of past abuse fundamentally undermines his position. The individual\'s right to refuse contact is rooted in self-preservation and the need to prioritize their mental health. Ethical frameworks that emphasize autonomy and the importance of consent support the conclusion that the individual is not an "asshole" for wanting to maintain distance from an abusive parent. Ultimately, the decision to refuse contact is reasonable given the context of past trauma and the father\'s failure to take responsibility for his actions.\n Therefore the author is doing the RIGHT thing.</think><O>RIGHT</O><|endoftext|>\n',
 '__index_level_0__': 0}

### 6.2. Trainer Setup

In [47]:
from trl import SFTTrainer, SFTConfig
import torch

trainer = SFTTrainer(
    model = model,
    processing_class = tokenizer,
    train_dataset = sft_dataset,
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 8,  # was 64 (only 3 optimizer steps for 100 samples)
        warmup_steps = 5,
        num_train_epochs = 2,
        max_seq_length = max_seq_length,
        learning_rate = 2e-4,
        logging_steps = 5,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        report_to = "none",
        output_dir = "outputs_sft",
    ),
)

# Unsloth tokenises from the 'text' column during __init__ but does not
# remove it; drop it here so the collator only sees input_ids/attention_mask/labels.
if "text" in trainer.train_dataset.column_names:
    trainer.train_dataset = trainer.train_dataset.remove_columns(["text"])

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/617 [00:00<?, ?B/s]

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/15 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

### 6.3. Train the model

In [48]:
import torch

# Ensure the model is on CUDA
if torch.cuda.is_available():
    model.to("cuda")

trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151654}.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 15 | Num Epochs = 2 | Total steps = 4
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 33,030,144 of 4,055,498,240 (0.81% trained)
`use_return_dict` is deprecated! Use `return_dict` instead!

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

TrainOutput(global_step=4, training_loss=1.8535199165344238, metrics={'train_runtime': 71.4537, 'train_samples_per_second': 0.42, 'train_steps_per_second': 0.056, 'total_flos': 625746737541120.0, 'train_loss': 1.8535199165344238, 'epoch': 2.0})

## 7. GRPO Training

### 7.1. Reward definition

**Regex rules** are defined so that the model is capable of recognising the desired patterns.

In [49]:
def extract_model_answer(content):
    """
    Extract the text between the first and second <|endoftext|> tags from a file.

    Args:
        file_path (str): Path to the file containing the text

    Returns:
        str: The extracted text between the tags
    """
    try:
        # Find the positions of the endoftext tags
        first_tag = content.find('<|endoftext|>')
        if first_tag == -1:
            return "First <|endoftext|> tag not found."

        # Find the second tag starting from after the first tag
        start_pos = first_tag + len('<|endoftext|>')
        second_tag = content.find('<|endoftext|>', start_pos)
        if second_tag == -1:
            return "Second <|endoftext|> tag not found."

        # Extract the text between the tags
        extracted_text = content[start_pos:second_tag]

        return extracted_text

    except Exception as e:
        return f"Error occurred: {str(e)}"

In [50]:
# Add optional EOS token matching
solution_end_regex = r"</O>[\s]{0,}" + \
    "(?:" + re.escape(tokenizer.eos_token) + ")?"

match_format = re.compile(
    rf"{reasoning_end}.*?"\
    rf"{solution_start}(.+?){solution_end_regex}"\
    rf"[\s]{{0,}}$",
    flags = re.MULTILINE | re.DOTALL
)
match_format

endoftext_pattern = re.compile(r'<\|endoftext\|>(.*?)<\|endoftext\|>', re.DOTALL)
think_pattern = re.compile(r'(.*?)<O>', re.DOTALL)
output_pattern = re.compile(r'<O>(.*?)</O>', re.DOTALL)

In the following cells, the **reward function** is designed and implemented.

In [51]:
def match_format_exactly(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        # Match if format is seen exactly!
        if match_format.search(response) is not None: score += 3.0
        scores.append(score)
    return scores

In [52]:
global PRINTED_TIMES
PRINTED_TIMES = 0
global PRINT_EVERY_STEPS
PRINT_EVERY_STEPS = 5

def check_verdict(prompts, completions, answer, **kwargs):
    question = prompts[0][-1]["content"]
    responses = [completion[0]["content"] for completion in completions]

    extracted_responses = [
        guess.group(1)
        if (guess := output_pattern.search(r)) is not None else None \
        for r in responses
    ]

    scores = []
    # Print only every few steps
    global PRINTED_TIMES
    global PRINT_EVERY_STEPS
    if PRINTED_TIMES % PRINT_EVERY_STEPS == 0:
        print(
            '*'*20 + f"Question:\n{question}", f"\nAnswer:\n{answer[0]}", f"\nResponse:\n{responses[0]}", f"\nExtracted:\n{extracted_responses[0]}"
        )
    PRINTED_TIMES += 1

    for guess, true_answer in zip(extracted_responses, answer):
        if guess is None:
            scores.append(-2.5)
            continue
        # Convert to numbers
        try:
            scores.append(3.5 if true_answer.upper() in guess.upper() else -1.5)
        except:
            scores.append(0)
            continue
    return scores

If it **fails**, the model will be rewarded for following the format at least partially. This is achieved by **counting each symbol**.

In [53]:
def match_format_approximately(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]

        #score += 1 if response.count(reasoning_start) == 1 else -1.5
        score += 0.5 if response.count(reasoning_end)   == 1 else -1.0
        score += 1 if response.count(solution_start)  == 1 else -1.5
        score += 0.5 if response.count(solution_end)    == 1 else -1.0
        scores.append(score)
    return scores

All that is left to do is to **extract the generated answer** and **reward** it or **penalise** it! The model is also rewarded based on how **close** the answer is to the annotated one through *ratios*.

In [54]:
def get_system_prompt():

    system_prompt = """
    You are a cognitive psychologist specializing in decision-making and reasoning assessment, you will evaluate the quality of analytical reasoning in "Am I The Asshole" case analyses. Your evaluation aims to identify cognitive biases, logical structures, and psychological underpinnings of the reasoning process.

    IMPORTANT: IF THE REASONING IS INCOHERENCE AND REALLY NOISY GIVE 0 IN ALL CRITERIA.

    EVALUATION CRITERIA:

    Each criterion is scored on a scale of 0-10 based on psychological principles of sound reasoning.
    1. NEUTRALITY (0-10): Assessment of cognitive bias and perspective-taking ability
    - 0-2: Severe fundamental attribution error; attributes negative motives to one party while excusing another's similar behavior
    - 3-4: Demonstrates significant confirmation bias, seeking evidence that supports preconceived judgment
    - 5-6: Shows moderate actor-observer bias but attempts perspective-taking
    - 7-8: Displays good psychological distancing with minimal in-group favoritism
    - 9-10: Exhibits exceptional cognitive empathy and perspective-taking abilities across all parties
    2. EVIDENCE_INTEGRATION (0-10): Cognitive processing of available information
    - 0-2: Severe availability bias; focuses only on salient or recent information
    - 3-4: Shows anchoring bias; overly influenced by first or strongest impressions
    - 5-6: Demonstrates selective attention but includes major evidence points
    - 7-8: Displays good information processing with minimal cherry-picking
    - 9-10: Exhibits comprehensive information synthesis, including subtle contextual cues and metacognitive awareness of evidence quality
    3. HYPOTHESIS_TESTING (0-10): Cognitive flexibility and consideration of alternatives
    - 0-2: Strong belief perseverance; fails to consider alternative explanations
    - 3-4: Minimal cognitive flexibility; briefly acknowledges alternatives without exploration
    - 5-6: Moderate hypothesis generation with uneven evaluation (satisficing)
    - 7-8: Good falsification testing; actively seeks disconfirming evidence
    - 9-10: Exceptional counter-factual thinking with systematic evaluation of multiple causal models
    4. LOGICAL_COHERENCE (0-10): Structure and validity of cognitive reasoning chains
    - 0-2: Demonstrates illusory correlation or post hoc fallacies
    - 3-4: Shows conjunction fallacy or base rate neglect in probabilistic reasoning
    - 5-6: Generally coherent with occasional modus ponens errors or hasty generalizations
    - 7-8: Strong syllogistic reasoning with minor imperfections
    - 9-10: Exemplary deductive and inductive reasoning without cognitive fallacies
    5. NUANCE_RECOGNITION (0-10): Tolerance for ambiguity and cognitive complexity
    - 0-2: Black-and-white thinking characteristic of cognitive rigidity
    - 3-4: Low tolerance for ambiguity; forces complex situations into simple frameworks
    - 5-6: Moderate recognition of complexity but still seeks premature cognitive closure
    - 7-8: Good integration of emotional and contextual factors in judgment
    - 9-10: High integrative complexity; recognizes dialectical tensions and multiple valid perspectives
    6. DECISION_ALIGNMENT (0-10): Metacognitive consistency and rational judgment process
    - 0-2: Severe cognitive dissonance between analysis and conclusion
    - 3-4: Motivated reasoning evident in selectively weighing evidence
    - 5-6: General alignment with some unjustified inferential leaps
    - 7-8: Good metacognitive awareness with most key factors appropriately weighted
    - 9-10: Exceptional rational decision process with explicit weighting of competing values


    SCORING CALCULATION:
    - Individual scores: Each criterion receives a score from 0-10
    - TOTAL_SCORE: Sum of all individual criterion scores (0-60)
    - COGNITIVE_QUALITY_RATING:
    * 0-20: SEVERELY_IMPAIRED_REASONING
    * 21-35: MODERATELY_IMPAIRED_REASONING
    * 36-50: FUNCTIONAL_REASONING
    * 51-60: OPTIMAL_REASONING
    OUTPUT FORMAT:
    {{{{
    "NEUTRALITY": <score>,
    "EVIDENCE_INTEGRATION": <score>,
    "HYPOTHESIS_TESTING": <score>,
    "LOGICAL_COHERENCE": <score>,
    "NUANCE_RECOGNITION": <score>,
    "DECISION_ALIGNMENT": <score>,
    "TOTAL_SCORE": <sum>,
    "COGNITIVE_QUALITY_RATING": "<rating>",
    "PSYCHOLOGICAL_ASSESSMENT": {{{{
        "NEUTRALITY": {{{{
        "cognitive_strengths": <"specific strength with example">,
        "cognitive_biases": <"specific bias with example">,
        "improvement_suggestions": <"specific suggestion">
        }}}},
        <repeat for all criteria>
    }}}},
    "SUMMARY_DIAGNOSIS": "Brief psychological assessment of overall reasoning pattern and primary cognitive strengths/limitations"
    }}}}

    EVALUATION PROCESS:
    1. Conduct thorough cognitive assessment of the reasoning process
    2. Identify specific psychological mechanisms, biases, and heuristics evident in the reasoning
    3. Evaluate reasoning against normative standards of rational decision-making
    4. Provide constructive feedback framed in terms of cognitive psychology principles
    5. Maintain professional, objective stance without pathologizing reasonable variations in thinking styles
    6. Do NOT put scores into brackets.
    7. Take into account the length of the reasoning trace.
    8. IMPORTANT: Check if the reasoning reach an conclusion and is aligned with the conclusion, if not penalize the DECISION_ALIGNMENT.
    9. IMPORTANT: Check if the reasoning incorporate different perspectives, if not penalize the NEUTRALITY.
    10. IMPORTANT: Check if the reasoning follows a coherent flow, if not penalize the LOGICAL_COHERENCE.
    11. IMPORTANT: Check if the reasoning is nuanced, if not penalize the NUANCE_RECOGNITION.
    12. IMPORTANT: Penalize all criteria if the reasoning if it is incoherent, short or really noisy.
    13. IMPORTANT: Check if the reasoning is aligned with the story, if not penalize all criteria.


    As a input you will be given the following:
    - The original AITA case text story, which will be given after "Original AITA case:"
    - The reasoning analysis to be evaluated, which will be given after "Reasoning to evaluate:"

    IMPORTANT: FOCUS TO EVALUATE TE REASONING NOT THE STORY.
    IMPORTANT: IF THE REASONING IS INCOHERENCE AND REALLY NOISY GIVE 0 IN ALL CRITERIA.
    IMPORTANT: CHECK THE REASONING DETAILY ACCORDING TO THE PROVIDED STORY, IF THEY ARE NOT RELATED GIVE 0 IN ALL CRITERIA.
    IMPORTANT: IF THE REASONING DOES NOT REACH A CLEAR CONCLUSION OF IF THE SPEACKER IS WRONG OR RIGHT GIVE PENALIZE DECISION_ALIGNMENT.
    """
    return system_prompt

def generate_prompt(story, reasoning):
    """
    Creates a prompt that evaluates the quality of reasoning in an AITA case.

    Parameters:
    -----------
    story : str
        The original AITA case text

    reasoning : str
        The reasoning analysis to be evaluated

    target_decision : str
        The expected judgment (RIGHT or WRONG)

    Returns:
    --------
    An evaluation of the reasoning quality with scores on six cognitive dimensions
    """

    prompt = f"""
    Evaluate the reasoning quality in the following AITA case analysis.

    Original AITA case:
    ---
    {story}
    ---

    Reasoning to evaluate:
    ---
    {reasoning}
    ---

    Return your evaluation in JSON format with scores for NEUTRALITY, EVIDENCE_INTEGRATION,
    HYPOTHESIS_TESTING, LOGICAL_COHERENCE, NUANCE_RECOGNITION, DECISION_ALIGNMENT,
    plus TOTAL_SCORE and QUALITY_RATING.

    IMPORTANT: IF THE REASONING IS INCOHERENCE, SHORT OR REALLY NOISY GIVE 0 IN ALL CRITERIA.

    Include brief explanations for each score that identify specific strengths and weaknesses
    in the reasoning process.
    """

    return prompt

In [55]:
def calculate_optimized_reward(assessment_output):
    """
    Calculate an optimized reward value based on cognitive reasoning assessment output.
    Uses a balanced hybrid approach with priority boosts for important criteria.

    Args:
        assessment_output (dict): The assessment output following the evaluation criteria

    Returns:
        float: A reward value between 0.0 and 1.0, with higher values for better reasoning
    """

    # Extract individual scores and validate they are numbers
    score_keys = ["NEUTRALITY", "EVIDENCE_INTEGRATION", "HYPOTHESIS_TESTING",
                 "LOGICAL_COHERENCE", "NUANCE_RECOGNITION", "DECISION_ALIGNMENT"]

    scores = {}
    for key in score_keys:
        value = assessment_output.get(key, 0)
        # Check if value is numeric or can be converted to a number
        if isinstance(value, (int, float)):
            scores[key] = value
        else:
            try:
                scores[key] = float(value)
            except (ValueError, TypeError):
              try:
                scores[key] = float(value[0])
              except (ValueError, TypeError):
                raise ValueError(f"Score '{key}' with value '{value}' is not a number and cannot be converted to one.")

    # Extract validated scores
    neutrality = scores["NEUTRALITY"]
    evidence_integration = scores["EVIDENCE_INTEGRATION"]
    hypothesis_testing = scores["HYPOTHESIS_TESTING"]
    logical_coherence = scores["LOGICAL_COHERENCE"]
    nuance_recognition = scores["NUANCE_RECOGNITION"]
    decision_alignment = scores["DECISION_ALIGNMENT"]

    # Define importance weights for each criterion
    # Higher weights for more important criteria
    importance_weights = {
        "NEUTRALITY": 1.3,         # 20% more important
        "EVIDENCE_INTEGRATION": 1.3, # 10% more important
        "HYPOTHESIS_TESTING": 0.9,   # 20% more important
        "LOGICAL_COHERENCE": 1.1,    # baseline importance
        "NUANCE_RECOGNITION": 0.9,   # slightly less important
        "DECISION_ALIGNMENT": 1    # 10% more important
    }

    # Apply importance weights to individual scores
    weighted_scores = {
        "NEUTRALITY": neutrality * importance_weights["NEUTRALITY"],
        "EVIDENCE_INTEGRATION": evidence_integration * importance_weights["EVIDENCE_INTEGRATION"],
        "HYPOTHESIS_TESTING": hypothesis_testing * importance_weights["HYPOTHESIS_TESTING"],
        "LOGICAL_COHERENCE": logical_coherence * importance_weights["LOGICAL_COHERENCE"],
        "NUANCE_RECOGNITION": nuance_recognition * importance_weights["NUANCE_RECOGNITION"],
        "DECISION_ALIGNMENT": decision_alignment * importance_weights["DECISION_ALIGNMENT"]
    }

    # Calculate weighted total score (0-60 scaled by importance)
    raw_total = neutrality + evidence_integration + hypothesis_testing + logical_coherence + nuance_recognition + decision_alignment
    weighted_total = sum(weighted_scores.values())
    max_possible_weighted = sum(10 * weight for weight in importance_weights.values())

    if weighted_total == 0: return { "final_reward": 0}

    # Store original scores for reference
    original_scores = {
        "NEUTRALITY": neutrality,
        "EVIDENCE_INTEGRATION": evidence_integration,
        "HYPOTHESIS_TESTING": hypothesis_testing,
        "LOGICAL_COHERENCE": logical_coherence,
        "NUANCE_RECOGNITION": nuance_recognition,
        "DECISION_ALIGNMENT": decision_alignment
    }

    # COMPONENT 1 (40%): Sigmoid Reward with importance-weighted total
    # Non-linear reward using sigmoid function to emphasize medium-quality improvements
    # Adjust the midpoint (30) proportionally to account for importance weights
    midpoint = 30 * (sum(importance_weights.values()) / 6)
    sigmoid_reward = 1.0 / (1.0 + math.exp(-0.15 * (weighted_total - midpoint)))

    # COMPONENT 2 (20%): Threshold Reward
    # Discrete reward levels based on cognitive quality rating
    thresholds = {
        "SEVERELY_IMPAIRED_REASONING": 0.1,  # (0-20 points)
        "MODERATELY_IMPAIRED_REASONING": 0.4,  # (21-35 points)
        "FUNCTIONAL_REASONING": 0.7,  # (36-50 points)
        "OPTIMAL_REASONING": 1.0,  # (51-60 points)
    }

    cognitive_quality = assessment_output.get("COGNITIVE_QUALITY_RATING", "")
    # Check if cognitive_quality is a valid key in thresholds
    if cognitive_quality not in thresholds and cognitive_quality != "":
        try:
            # See if it's a string representation of a number
            threshold_reward = float(cognitive_quality) / 60.0
        except (ValueError, TypeError):
            # If not a valid key or number, default to raw_total based calculation
            threshold_reward = raw_total / 60.0
    else:
        threshold_reward = thresholds.get(cognitive_quality, raw_total / 60.0)

    # COMPONENT 3 (20%): Minimum Criterion Reward
    # Rewards based on the weakest aspect of reasoning
    # Use original unweighted scores to find the weakest criterion
    min_criterion_score = min(original_scores.values())
    min_criterion_reward = min_criterion_score / 10.0  # Normalize to 0-1

    # COMPONENT 4 (20%): Variance Reward
    # Rewards balanced reasoning across all criteria
    # Use original unweighted scores to calculate variance
    scores_list = list(original_scores.values())
    variance = np.var(scores_list)
    # Maximum possible variance for six scores on a 0-10 scale
    max_possible_variance = 33.33  # Theoretical max with most extreme distribution
    variance_reward = 1.0 - (variance / max_possible_variance)

    # Calculate optimized hybrid reward with component weights
    optimized_reward = (
        0.4 * sigmoid_reward +       # 40% weight - primary non-linear signal (with importance weighting)
        0.2 * threshold_reward +     # 20% weight - quality tier recognition
        0.2 * min_criterion_reward + # 20% weight - weakest aspect emphasis
        0.2 * variance_reward        # 20% weight - balanced reasoning emphasis
    )

    # Add boost for high scores in priority criteria
    priority_criteria = ["NEUTRALITY", "HYPOTHESIS_TESTING", "DECISION_ALIGNMENT"]
    boost_threshold = 8  # Apply boost for scores of 8 or higher in priority criteria
    boost_value = 0.0

    for criterion in priority_criteria:
        if original_scores[criterion] >= boost_threshold:
            boost_value += 0.02  # 2% boost per high-scoring priority criterion

    # Apply boost to final reward (capped at 1.0)
    final_reward = min(1.0, optimized_reward + boost_value)

    # Return detailed breakdown for analysis
    return {
        "component_rewards": {
            "sigmoid_reward": sigmoid_reward,
            "threshold_reward": threshold_reward,
            "min_criterion_reward": min_criterion_reward,
            "variance_reward": variance_reward
        },
        "component_weights": {
            "sigmoid_weight": 0.4,
            "threshold_weight": 0.2,
            "min_criterion_weight": 0.2,
            "variance_weight": 0.2
        },
        "importance_weights": importance_weights,
        "priority_boost": boost_value,
        "raw_total": raw_total,
        "weighted_total": weighted_total,
        "optimized_reward": optimized_reward,
        "final_reward": final_reward
    }

In [56]:
def parse_json_response(response_text):
    """
    Attempts to parse a JSON response, handling common issues.

    Parameters:
    -----------
    response_text : str
        The text response from an LLM

    Returns:
    --------
    dict or None: The parsed JSON or None if parsing failed
    """
    # Strip any markdown code block syntax
    cleaned_text = re.sub(r'^```json\s*', '', response_text)
    cleaned_text = re.sub(r'\s*```$', '', cleaned_text)

    # Try to find JSON object if there's extra text
    json_pattern = r'\{[\s\S]*\}'
    json_match = re.search(json_pattern, cleaned_text)

    if json_match:
        json_str = json_match.group(0)
        try:
            return json.loads(json_str)
        except json.JSONDecodeError:
            return None

    # If no JSON object pattern found, try the whole text
    try:
        return json.loads(cleaned_text)
    except json.JSONDecodeError:
        return None

def check_reasoning(prompts, completions, **kwargs):
    """
    Evaluates the reasoning quality in model completions.

    Parameters:
    -----------
    prompts : list
        List of prompts where each prompt is a list of messages
    completions : list
        List of completions where each completion is a list of messages

    Returns:
    --------
    list: A list of reward scores
    """
    # Extract the question (story) from the prompt
    question = prompts[0][-1]["content"]

    # Extract the responses
    responses = [completion[0]["content"] for completion in completions]

    extracted_responses = []

    for r in responses:
        reasoning = match_format.search(r)
        if reasoning is not None:
            extracted_responses.append(reasoning.group(1))
        else:
            reasoning = think_pattern.search(r)
            if reasoning is not None:
                extracted_responses.append(reasoning.group(1))
            else:
                extracted_responses.append(None)

    # Get the system prompt for evaluation
    system_prompt = get_system_prompt()

    # Process each response and calculate rewards
    all_rewards = []

    for reasoning in extracted_responses:
        if reasoning is None:
            all_rewards.append(0)
            continue

        if len(reasoning) < 10:
            all_rewards.append(-1)
            continue


        # Try to extract reasoning if needed (adjust based on your model's output format)
        extracted_reasoning = reasoning

        # Generate the evaluation prompt
        user_prompt = generate_prompt(question, extracted_reasoning)

        # Try parsing and calculating rewards for up to 3 attempts
        reward_calculated = False
        max_attempts = 3

        for attempt in range(max_attempts):
            try:
                # Run the evaluation (if need be, the user may add to use_chain=True)
                response = gpt_chat.run(
                    prompt=user_prompt,
                    system_prompt=system_prompt
                )

                # Parse the response
                assessment = parse_json_response(response)

                # If successfully parsed, try to calculate reward
                if assessment is not None:
                    try:
                        # Attempt to calculate reward
                        reward_results = calculate_optimized_reward(assessment)
                        all_rewards.append(reward_results["final_reward"]*10)
                        reward_calculated = True
                        break
                    except ValueError as e:
                        print(f"Reward calculation failed on attempt {attempt+1}: {str(e)}")
                else:
                    print(f"Failed to parse JSON on attempt {attempt+1}")

                    if attempt < max_attempts - 1:
                        # Modify the prompt to emphasize JSON formatting
                        user_prompt += "\n\nPlease ensure your response is in valid JSON format with numeric values only for all metrics."

            except Exception as e:
                print(f"Attempt {attempt+1} failed with error: {str(e)}")
                # Short delay before retrying to avoid rate limits
                time.sleep(1)

        # If we exited the loop without calculating a reward, add zero
        if not reward_calculated:
            print("Failed to calculate reward after all attempts. Returning zero reward.")
            all_rewards.append(0.0)

    return all_rewards

### 7.2. Defining the teacher model

In [67]:
import os
from typing import Optional, Union

# LangChain imports
from langchain_core.language_models import BaseLanguageModel, BaseChatModel
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import HumanMessage, SystemMessage

class Chat:
    def __init__(self, model_name: str, api_key: Optional[str] = None, base_url: Optional[str] = None, verbose: bool = False, temperature: float = 0.1):
        self.model_name = model_name
        self.api_key = api_key
        self.base_url = base_url # This can be None, will use default in _initialize_model
        self.verbose = verbose
        self.temperature = temperature # Store temperature
        self.llm = self._initialize_model()


    def _initialize_model(self) -> Union[BaseChatModel, BaseLanguageModel]:
        """Initialize the appropriate language model based on the model name."""
        # Handle OpenAI models
        if "gpt" in self.model_name.lower() or "openai" in self.model_name.lower():
            from langchain_openai import ChatOpenAI

            return ChatOpenAI(
                model_name=self.model_name,
                openai_api_key=self.api_key,
                temperature=self.temperature # Use self.temperature
            )

        # Handle Anthropic models
        elif "anthropic" in self.model_name.lower() or "claude" in self.model_name.lower():
            from langchain_anthropic import ChatAnthropic
            return ChatAnthropic(
                model_name=self.model_name,
                anthropic_api_key=self.api_key,
                temperature=self.temperature
            )

        # Handle Google Gemini models
        elif "gemini" in self.model_name.lower() or "google" in self.model_name.lower():
            from langchain_google_genai import ChatGoogleGenerativeAI
            return ChatGoogleGenerativeAI(
                model=self.model_name,
                google_api_key=self.api_key,
                temperature=self.temperature
            )

        # Handle Ollama models
        elif "ollama" in self.model_name.lower() or self.model_name.lower() in ["gemma", "llama", "mistral", "vicuna", "phi"]:
            from langchain_ollama.llms import OllamaLLM
            # Extract the actual model name if "ollama:" prefix is used
            ollama_model = self.model_name
            if "ollama:" in self.model_name.lower():
                ollama_model = self.model_name.split(":", 1)[1]
            if self.base_url:
                return OllamaLLM(
                    model=ollama_model,
                    base_url=self.base_url,
                    temperature=self.temperature
                )
            else:
                return OllamaLLM(
                    model=ollama_model,
                    temperature=self.temperature
                )

        # Handle HuggingFace models via InferenceClient.text_generation()
        # HuggingFaceEndpoint used InferenceClient.post() which was removed in huggingface_hub>=0.25
        elif self.model_name.lower().startswith("meta-llama/") or "huggingface" in self.model_name.lower():
            from langchain_core.language_models import BaseLLM
            from langchain_core.outputs import LLMResult, Generation

            _model_name = self.model_name
            _api_key    = self.api_key
            _temp       = max(self.temperature, 0.01)

            class _HFDirectLLM(BaseLLM):
                model_name:  str   = _model_name
                api_key:     str   = _api_key
                max_tokens:  int   = 1024
                temperature: float = _temp

                @property
                def _llm_type(self) -> str:
                    return "huggingface-direct"

                def _generate(self, prompts, stop=None, run_manager=None, **kwargs):
                    from huggingface_hub import InferenceClient
                    client = InferenceClient(model=self.model_name, token=self.api_key)
                    gens = []
                    for p in prompts:
                        text = client.text_generation(
                            p,
                            max_new_tokens=self.max_tokens,
                            temperature=self.temperature,
                            do_sample=True,
                        )
                        gens.append([Generation(text=text)])
                    return LLMResult(generations=gens)

            return _HFDirectLLM()

        else:
            error_msg = f"Unsupported model: {self.model_name}"
            raise ValueError(error_msg)

    def run(self, prompt: str, system_prompt: Optional[str] = None, use_chain: bool = False) -> str:
        """Run a completion using a list of messages or a chain, based on use_chain parameter."""

        if use_chain:
            # Existing LCEL chain approach (for ChatModels)
            if isinstance(self.llm, BaseChatModel):
                if system_prompt:
                    prompt_template = ChatPromptTemplate.from_messages([
                        ("system", system_prompt),
                        ("human", "{input}")
                    ])
                else:
                    prompt_template = ChatPromptTemplate.from_messages([
                        ("human", "{input}")
                    ])
                chain = prompt_template | self.llm
                try:
                    response = chain.invoke({"input": prompt})
                    if hasattr(response, 'content'):
                        return response.content
                    else:
                        return str(response)
                except Exception as e:
                    raise RuntimeError(f"Error invoking chain with ChatModel: {str(e)}")
            elif isinstance(self.llm, BaseLanguageModel):
                # For BaseLanguageModel, concatenate and invoke directly, even if use_chain is True
                full_prompt = ""
                if system_prompt:
                    full_prompt += system_prompt + "\n\n"
                full_prompt += prompt
                try:
                    response = self.llm.invoke(full_prompt)
                    return response
                except Exception as e:
                    raise RuntimeError(f"Error invoking chain with LanguageModel: {str(e)}")
            else:
                raise ValueError("Unsupported LLM type in Chat class for chain invocation.")
        else:
            # Direct invocation with message objects or string, based on LLM type
            if isinstance(self.llm, BaseChatModel):
                messages = []
                if system_prompt:
                    messages.append(SystemMessage(content=system_prompt))
                messages.append(HumanMessage(content=prompt))
                try:
                    response = self.llm.invoke(messages)
                    if hasattr(response, 'content'):
                        return response.content
                    else:
                        return str(response)
                except Exception as e:
                    raise RuntimeError(f"Error invoking ChatModel directly: {str(e)}")
            elif isinstance(self.llm, BaseLanguageModel):
                full_prompt = ""
                if system_prompt:
                    full_prompt += system_prompt + "\n\n"
                full_prompt += prompt
                try:
                    response = self.llm.invoke(full_prompt)
                    return response
                except Exception as e:
                    raise RuntimeError(f"Error invoking LanguageModel directly: {str(e)}")
            else:
                raise ValueError("Unsupported LLM type in Chat class for direct invocation.")

#### 7.2.1. Choosing the base trainer model

There are many options to choose from when faced with the decision of which model to use as the cloud-based teacher model. The following list narrows the consideration to very few, very utilitarian factors: its _potency_ and its _pricing_. Given that it is cloud-based, the solution ought not take into account local hardware limitations.

1. [_OpenAI_ API](https://openai.com/api/):

    1.1. **GPT-4o-mini**: it is fast, reliable, and deeply integrated into _LangChain_. It is quite cheap (0.15 American dollars/M input, 0.60 American dollars/M output) and offers [_Researcher Access_](https://openai.com/form/researcher-access-program/) programs to which one may apply through a university.

2. [_Anthropic_ API](https://platform.claude.com/docs/en/about-claude/models/overview):

    2.1. **Claude 3.5 Sonnet**: it is a very potent model; arguably, the best one on the market for fine, complex philosophical reasoning and strict rubric adherence. It has one of the highest pricings on this list (3 American dollars/M input tokens, 15 American dollars/M output tokens).

    2.2. **Claude 3.5 Haiku**: it is _Anthropic_'s fastest model, yet it retains much of what gives the Claude line its quality. It is notably cheaper than Sonnet (0.25 American dollars/M input, 1.25 American dollars/M output).

3. [_Google AI Studio_ API](https://ai.google.dev/gemini-api/docs/pricing):

    3.1. **Google Gemini 1.5 Flash**: it is fast and has a big context window. It is one of the cheaper options in this list (0.075 American dollars/M input, 0.30 American dollars/M output) and it offers a free tier (up to 15 requests per minute, 1M tokens per minute; _this will not be enough to train the teacher model, but it is a good option for preliminarily trying out the code's integrity_).

4. [_DeepSeek_ API](https://deepseekapi.io/):

    4.1. **DeepSeek-V3**: it has good reasoning capabilities, comparable to GPT-4o. It is one of the cheapest options in this list (0.14 American dollars/M input, 0.28 American dollars/M output).

**The list might be incomplete, outdated or wrong**, more so as time passes. Feel free to update it or ignore it altogether.

#### 7.2.2. I have the key!

In Google Colab, the user has the option to access the **Secrets** panel (fourth icon from the top in the left sidebar, a **key**). In order to run the code without changing the existing configuration, the user will have to do the following **before running the cell**:

1. Click on _+ Add a new secret_ and allow for _Notebook access_ (toggle right).
2. _Name_ the secret `GOOGLE_API_KEY` and assign to it the **API key** in the _Value_ field.

Alternatively, if the user is running this code in a **local** environment, they will have to set the environment variable `GOOGLE_API_KEY` before launching Jupyter.

#### 7.2.3. An alternative: HuggingFace

To use `Llama 3`, the user will need to ensure they have **legal right** to use the weights and that their code can *prove* their identity to HuggingFace. To achieve this, the following steps should be followed:

#### Request Access

1. Go to the [Meta-Llama-3-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct) page on HuggingFace.
2. Log in to a HuggingFace account (or create one).
3. **Read and accept the license agreement** in [Meta-Llama-3-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct).
4. Wait for approval. Usually, this is *instantaneous*, but an email should arrive for a confirmation from Meta.

#### Create a Read Token
1. Navigate to HuggingFace [Access Tokens Settings](https://huggingface.co/settings/tokens).
2. Click **Create new token**, set the **Type** to **Read** (if the code still fails, **Write** might be necessary) and name it.
3. Click **Create token** and **copy it immediately**, as it will *not be shown again!*

The following cell replaces the *Login* manual step and prevents the `401 Client Error`. To access HuggingFace's key, the user should follow the same instructions as in **7.2.2**, replacing `GOOGLE_API_KEY` for `HF_KEY`.

In [58]:
import os
from huggingface_hub import login
from google.colab import userdata

HF_TOKEN = ""
GOOGLE_API_KEY = ""

if IS_COLAB:
    try:
        HF_TOKEN = userdata.get("HF_KEY")
        if not HF_TOKEN:
            print("WARNING: HF_KEY not found in Colab Secrets or is empty.")
    except Exception as e:
        print(f"Could not load HF_KEY from Colab Secrets: {e}")

    try:
        GOOGLE_API_KEY = userdata.get("GOOGLE_API_KEY")
        if not GOOGLE_API_KEY:
            print("WARNING: GOOGLE_API_KEY not found in Colab Secrets or is empty.")
    except Exception as e:
        print(f"Could not load GOOGLE_API_KEY from Colab Secrets: {e}")

else:
    HF_TOKEN = os.environ.get("HF_KEY", "")
    GOOGLE_API_KEY = os.environ.get("GOOGLE_API_KEY", "")

if not HF_TOKEN and not GOOGLE_API_KEY:
    print("WARNING: No API keys found. Set keys before running training.")

# Teacher model initialisation
gpt_chat = None
try:
  if HF_TOKEN:
    login(token=HF_TOKEN, add_to_git_credential=True)
    MODEL_NAME = "meta-llama/Meta-Llama-3-8B-Instruct"
    gpt_chat = Chat(model_name=MODEL_NAME, api_key=HF_TOKEN, verbose=False)
    print(f"Teacher model initialised: {MODEL_NAME}")
  else:
    raise ValueError("HF_TOKEN is not available, falling back to Gemini.") # HF_TOKEN is empty

except Exception as e:
  print(f"HuggingFace model initialization failed: {e}. Falling back to Gemini.")
  MODEL_NAME = "gemini-2.0-flash" # "gemini-2.0-flash" is recommended; "gemini-1.5-flash" is a stable fallback

  if GOOGLE_API_KEY:
      gpt_chat = Chat(model_name=MODEL_NAME, api_key=GOOGLE_API_KEY, verbose=False)
      print(f"Teacher model initialised: {MODEL_NAME}")
  else:
      print("WARNING: GOOGLE_API_KEY is also not available. Cannot initialize Gemini model.")

if gpt_chat is None:
    raise RuntimeError("No teacher model could be initialized. Please check your API keys.")

Teacher model initialised: meta-llama/Meta-Llama-3-8B-Instruct

/tmp/ipykernel_2232/3364961029.py:75: LangChainDeprecationWarning: The class `HuggingFaceHub` was deprecated in LangChain 0.0.21 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEndpoint``.
  return HuggingFaceHub(

### 7.3. Preparing the GRPO dataset

In [59]:
n = 1000
wrong_subset = dataset[dataset['expected_answer'] == "WRONG"].head(n//2)
right_subset = dataset[dataset['expected_answer'] == "RIGHT"].head(n//2)
combined_dataset = pd.concat([wrong_subset, right_subset], ignore_index=True)
combined_dataset = combined_dataset.sample(frac=1).reset_index(drop=True)

grpo_dataset = Dataset.from_pandas(combined_dataset)

grpo_dataset = grpo_dataset.map(lambda x: {
    "prompt" : [
        {"role": "system", "content": system_prompt},
        {"role": "user",   "content": x["problem"]},
    ],
    "answer": x["expected_answer"],
})
grpo_dataset[0]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

{'expected_answer': 'WRONG',
 'problem': "So I (29M) dated this girl (27F) for a short period of time, but apart from anything platonic it didn't click, and we decided to be close friends since that part did click very well. I'm an aromantic/asexual, so to me that has hardly any other effect than relieving me from the chores related to dating. (nothing emotional on my side, basically ; she knows)\n\nExcept that whenever she starts dating someone she treats all of us friends like plan B. Especially with me, she becomes horribly distant and makes sure not to be seen hanging around me in familiar circles/treats me openly like a stranger unless it's incognito. (I get it, I'm an attractive male, my presence usually makes guys quite insecure when they chase, and there is clearly some feelings left on her side ; so...)\n\nNow, friendships mean the whole world to me and I really do my best to care for my friends. But I don't tolerate being «used», and I soon decided to skip being around her to help when her datings failed, and I just come back when she starts feeling better (whether or not I'm an asshole on this is a completely different debate). Ultimately, I got fed up about this, and decided to give her a few months no-contact period (to give her time to at least get rid of her feelings for me).\n\nI've been trying to reconnect with her for the last month, but she's displaying the same pattern as usually while dating (all checks for her actually wanting to be friends again are there, though). Yesterday, I heard by accident that she accepted some guy's proposal for a FWB, and since she's a hopeless romantic, I can already see how it's gonna fail pretty quick and she'll be a mess once again. The difference this time is that I don't think I would ever have a moral obligation to be there for her, since we haven't exactly properly reconnected yet.\n\nSo assuming we're talking about solely this time : assuming I really do want to reconnect, though, will I be an asshole for willingly failing to fulfill that part of being an actual friend ?",
 'generated_solution': 'The author of the story is navigating a complex friendship with a girl who exhibits patterns of behavior that are emotionally taxing for him. The primary issue is her tendency to treat him as a fallback option when her romantic relationships fail, which he finds unacceptable. He has chosen to distance himself during her dating periods, which he believes is a way to protect himself from being "used." \n\n1. **Hypothesis 1: The author is justified in distancing himself.**\n   - Evidence for: He has communicated his feelings about being treated as a backup, and distancing himself may help him maintain his emotional well-being.\n   - Evidence against: By not being present for her during difficult times, he may be reinforcing her feelings of abandonment and could be seen as lacking empathy.\n\n2. **Hypothesis 2: The author should be there for her regardless of their friendship status.**\n   - Evidence for: True friendship often involves supporting one another through ups and downs, regardless of personal feelings.\n   - Evidence against: The author has made it clear that he does not want to be used, and being there for her could lead to further emotional distress for him.\n\n3. **Hypothesis 3: The author is being an "asshole" by not fulfilling his role as a friend.**\n   - Evidence for: Friends are expected to support each other, and his decision to withdraw could be perceived as selfish.\n   - Evidence against: He has a right to set boundaries for his own mental health, especially if he feels that the friendship is one-sided.\n\nOverall, while the author has valid reasons for his actions, the ethical implications of abandoning a friend in need complicate the situation.While the author feels justified in his decision to distance himself, it is essential to consider the broader implications of his actions. From a utilitarian perspective, the potential harm caused to the girl by his withdrawal could outweigh his personal discomfort. If he truly values the friendship, he might consider that being present for her during her struggles could foster a healthier dynamic in the long run. \n\nAdditionally, the author\'s self-identification as aromantic/asexual may lead him to underestimate the emotional complexities of their friendship. He may not fully grasp the impact of his absence on her emotional state, especially if she still harbors feelings for him. \n\nFurthermore, the idea of being an "asshole" can be subjective. While he may feel justified in his actions, it is crucial to recognize that friendships often require sacrifices and emotional labor, which he seems unwilling to provide. \n\nUltimately, while he has the right to protect his own emotional health, the ethical obligation to support a friend in distress remains significant.The author\'s decision to distance himself from the girl stems from a desire to protect his emotional well-being and avoid being used as a fallback. However, this choice raises ethical questions about the responsibilities inherent in friendships. While he has valid reasons for his actions, the potential emotional harm to the girl and the implications of abandoning a friend in need suggest that he may not be acting in alignment with the values of friendship. \n\nDespite his feelings of being used, true friendship often requires support during difficult times, which he is currently unwilling to provide. Therefore, while he may feel justified in his actions, the conclusion that he is doing the "wrong" thing is reasonable when considering the broader ethical implications and the potential impact on their friendship.\n Therefore the author is doing the WRONG thing.',
 'title': "WIBTA for once more not wanting to be an ex/friend's emotional cushion ?",
 'prompt': [{'role': 'system',
   'content': 'You are a helpful assistant.\nYou are given a dilemma. You must decide if the author is acting correctly according to moral reasoning.\nYou must consider these moral axioms, from top priority (1) to least (10):\n1.\tTo not kill innocent people.\n2.\tTo not cause unnecessary harm nor suffering.\n3.\tTo not deceive nor steal.\n4.\tTo comply with promises and honour one\'s agreements.\n5.\tTo not deprive anyone from freedom.\n6.\tTo act justly.\n7.\tTo be truthful.\n8.\tTo help others.\n9.\tTo be grateful.\n10.\tTo obey positive laws that are just.\nYou must accommodate as many axioms as possible. Answer \'No: \' and the numbers of the unapliccable axioms.\nDecide if the author is acting correctly in this moral reasoning in 100 characters or less.\nPlace your answer between <think> and </think>.\nThen answer "RIGHT" or "WRONG" within <O> and </O> as the final verdict.\n'},
  {'role': 'user',
   'content': "So I (29M) dated this girl (27F) for a short period of time, but apart from anything platonic it didn't click, and we decided to be close friends since that part did click very well. I'm an aromantic/asexual, so to me that has hardly any other effect than relieving me from the chores related to dating. (nothing emotional on my side, basically ; she knows)\n\nExcept that whenever she starts dating someone she treats all of us friends like plan B. Especially with me, she becomes horribly distant and makes sure not to be seen hanging around me in familiar circles/treats me openly like a stranger unless it's incognito. (I get it, I'm an attractive male, my presence usually makes guys quite insecure when they chase, and there is clearly some feelings left on her side ; so...)\n\nNow, friendships mean the whole world to me and I really do my best to care for my friends. But I don't tolerate being «used», and I soon decided to skip being around her to help when her datings failed, and I just come back when she starts feeling better (whether or not I'm an asshole on this is a completely different debate). Ultimately, I got fed up about this, and decided to give her a few months no-contact period (to give her time to at least get rid of her feelings for me).\n\nI've been trying to reconnect with her for the last month, but she's displaying the same pattern as usually while dating (all checks for her actually wanting to be friends again are there, though). Yesterday, I heard by accident that she accepted some guy's proposal for a FWB, and since she's a hopeless romantic, I can already see how it's gonna fail pretty quick and she'll be a mess once again. The difference this time is that I don't think I would ever have a moral obligation to be there for her, since we haven't exactly properly reconnected yet.\n\nSo assuming we're talking about solely this time : assuming I really do want to reconnect, though, will I be an asshole for willingly failing to fulfill that part of being an actual friend ?"}],
 'answer': 'WRONG'}

In [61]:
tokenized = grpo_dataset.map(
    lambda batch_of_examples: {
        "tokens": [
            tokenizer.apply_chat_template(
                prompt_messages,
                add_generation_prompt=True,
                tokenize=True
            ) for prompt_messages in batch_of_examples["prompt"]
        ]
    },
    batched=True,
)
print(tokenizer.decode(tokenized[0]["tokens"]))
tokenized = tokenized.map(lambda x: {"L" : len(x["tokens"])} )

maximum_length = int(np.quantile(tokenized["L"], 0.9))
print("Max Length = ", maximum_length)

# Filter only samples smaller than 90% max length
grpo_dataset = grpo_dataset.select(np.where(np.array(tokenized["L"]) <= maximum_length)[0])

# Reset the indices to be continuous
grpo_dataset = grpo_dataset.select(range(len(grpo_dataset)))
del tokenized

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

You are a helpful assistant.
You are given a dilemma. You must decide if the author is acting correctly according to moral reasoning.
You must consider these moral axioms, from top priority (1) to least (10):
1.	To not kill innocent people.
2.	To not cause unnecessary harm nor suffering.
3.	To not deceive nor steal.
4.	To comply with promises and honour one's agreements.
5.	To not deprive anyone from freedom.
6.	To act justly.
7.	To be truthful.
8.	To help others.
9.	To be grateful.
10.	To obey positive laws that are just.
You must accommodate as many axioms as possible. Answer 'No: ' and the numbers of the unapliccable axioms.
Decide if the author is acting correctly in this moral reasoning in 100 characters or less.
Place your answer between <think> and </think>.
Then answer "RIGHT" or "WRONG" within <O> and </O> as the final verdict.
<|endoftext|>
So I (29M) dated this girl (27F) for a short period of time, but apart from anything platonic it didn't click, and we decided to be close friends since that part did click very well. I'm an aromantic/asexual, so to me that has hardly any other effect than relieving me from the chores related to dating. (nothing emotional on my side, basically ; she knows)

Except that whenever she starts dating someone she treats all of us friends like plan B. Especially with me, she becomes horribly distant and makes sure not to be seen hanging around me in familiar circles/treats me openly like a stranger unless it's incognito. (I get it, I'm an attractive male, my presence usually makes guys quite insecure when they chase, and there is clearly some feelings left on her side ; so...)

Now, friendships mean the whole world to me and I really do my best to care for my friends. But I don't tolerate being «used», and I soon decided to skip being around her to help when her datings failed, and I just come back when she starts feeling better (whether or not I'm an asshole on this is a completely different debate). Ultimately, I got fed up about this, and decided to give her a few months no-contact period (to give her time to at least get rid of her feelings for me).

I've been trying to reconnect with her for the last month, but she's displaying the same pattern as usually while dating (all checks for her actually wanting to be friends again are there, though). Yesterday, I heard by accident that she accepted some guy's proposal for a FWB, and since she's a hopeless romantic, I can already see how it's gonna fail pretty quick and she'll be a mess once again. The difference this time is that I don't think I would ever have a moral obligation to be there for her, since we haven't exactly properly reconnected yet.

So assuming we're talking about solely this time : assuming I really do want to reconnect, though, will I be an asshole for willingly failing to fulfill that part of being an actual friend ?
{reasoning_start}

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Max Length =  884

### 7.4. Trainer Setup

In [62]:
import torch
from trl import GRPOConfig

max_prompt_length = maximum_length + 1  # +1 just in case
max_completion_length = max_seq_length - max_prompt_length

training_args = GRPOConfig(
    # NOTE: vllm_sampling_params intentionally omitted.
    #   fast_inference=False means vLLM is not loaded; including those params
    #   causes the trainer to crash when trying to access the vLLM engine.
    temperature = 1.0,
    num_generations = 2,                # was 4; halved to cut peak VRAM ~40%
    # max_prompt_length = max_prompt_length,
    max_completion_length = max_completion_length,

    learning_rate = 5e-6,
    weight_decay = 0.01,
    warmup_steps = 100,              # replaces warmup_ratio=0.1 (deprecated in trl v5.2)
    lr_scheduler_type = "linear",
    optim = "adamw_8bit",

    fp16 = not torch.cuda.is_bf16_supported(),
    bf16 = torch.cuda.is_bf16_supported(),

    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 4,
    max_steps = 1000,
    save_steps = 25,
    logging_steps = 1,

    report_to = "none",
    output_dir = "outputs",
)

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

### 7.5. Train the model

The `GRPOTrainer` class inherits from `transformers.Trainer`. The `transformers.Trainer` has the `_get_dataloader` method, which internally calls `self._get_train_sampler` to get the sampler for the training data. This internal call passes a dataset argument to `_get_train_sampler`.

It might happen, depending on the `transformers` version the user has installed, that `get_train_sampler` is **not available or has been moved** (and thus, cannot be imported through the given code). Attempting to find it is the purpouse of the following cell. **If it is there**, the exact module should be printed out and the user would only have to **adapt the corresponding import** in the cell immediatelly after.

However, there might be times that, independently from the `transformers` library's version, an error persists when trying to run the second cell. As a provision, an alternative way to load the dataset (which might be the source of the problem) has been implemented and should trigger as soon as the primary implementation fails.

In [63]:
import os
import transformers

# Path to library
file_path = transformers.__file__
dir = os.path.dirname(file_path)
dir_list = os.listdir(dir)

print(f"The library is in: {dir}")
print(f"The library has the following modules: {dir_list}\n")

module = 'get_train_sampler'
found = False

# Hereby starts the search for the method we will need next
for item in dir_list:
  if found:
    break
  current_path = os.path.join(dir, item)
  # Check if it is a file
  if os.path.isfile(current_path):
    try:
        with open(current_path, 'r', encoding='utf-8') as f:
            content = f.read()
            # Check whether the method is in this module
            if module in content:
                found = True
                print(f"{module} found in: {current_path}")
    except Exception as e:
        print(f"Could not read file {current_path}: {e}")
  # If it is not a file, pass
  else:
    pass

if not found:
    print(f"{module} not found in any files within the library's directory.")

The library is in: /usr/local/lib/python3.12/dist-packages/transformers
The library has the following modules: ['masking_utils.py', 'modeling_outputs.py', 'time_series_utils.py', 'pytorch_utils.py', 'trainer.py', 'video_utils.py', '__init__.py', 'trainer_jit_checkpoint.py', 'feature_extraction_utils.py', 'training_args_seq2seq.py', 'quantizers', 'convert_slow_tokenizer.py', 'tokenization_utils_tokenizers.py', '__pycache__', 'image_utils.py', 'trainer_seq2seq.py', 'distributed', 'tokenization_utils_sentencepiece.py', 'video_processing_utils.py', 'image_processing_utils.py', 'dynamic_module_utils.py', 'utils', 'training_args.py', 'image_processing_base.py', 'testing_utils.py', 'trainer_optimizer.py', 'model_debugging_utils.py', 'trainer_callback.py', 'modeling_utils.py', 'conversion_mapping.py', 'data', 'dependency_versions_table.py', 'safetensors_conversion.py', 'cache_utils.py', 'tokenization_python.py', 'hf_argparser.py', 'image_processing_backends.py', 'optimization.py', 'integrations', 'modeling_gguf_pytorch_utils.py', 'configuration_utils.py', 'generation', 'models', 'modelcard.py', 'modeling_flash_attention_utils.py', 'audio_utils.py', 'file_utils.py', 'processing_utils.py', '_typing.py', 'convert_slow_tokenizers_checkpoints_to_fast.py', 'trainer_pt_utils.py', 'backbone_utils.py', 'trainer_utils.py', 'loss', 'core_model_loading.py', 'cli', 'hyperparameter_search.py', 'tokenization_utils_base.py', 'modeling_rope_utils.py', 'tokenization_mistral_common.py', 'py.typed', 'debug_utils.py', 'initialization.py', 'modeling_attn_mask_utils.py', 'feature_extraction_sequence_utils.py', 'activations.py', 'modeling_layers.py', 'image_transforms.py', 'pipelines', 'dependency_versions_check.py', 'monkey_patching.py']

get_train_sampler found in: /usr/local/lib/python3.12/dist-packages/transformers/trainer.py

In [ ]:
import types
import torch
from torch.utils.data import RandomSampler
from datasets import Dataset
from trl import GRPOTrainer

def patched_get_train_sampler(self, dataset=None):
    if dataset is None:
        dataset = self.train_dataset
    try:
        from transformers.trainer_pt_utils import get_train_sampler
        return get_train_sampler(self.args, dataset)
    except Exception:
        generator = torch.Generator().manual_seed(self.args.seed) if self.args.seed else None
        return RandomSampler(dataset, generator=generator)

# Preserve prompt lists as-is: PyTorch default_collate transposes
# [[msg1,msg2],[msg3,msg4]] into [{role:[...],content:[...]},{...}],
# which breaks apply_chat_template. This collator keeps them intact.
class GRPODataCollator:
    def __call__(self, features):
        return {key: [f[key] for f in features] for key in features[0].keys()}

try:
    gpt_chat  # noqa: F821
    reward_funcs = [
        match_format_exactly,
        match_format_approximately,
        check_reasoning,
        check_verdict,
    ]
    print("Using all 4 reward functions (including teacher model).")
except NameError:
    reward_funcs = [
        match_format_exactly,
        match_format_approximately,
        check_verdict,
    ]
    print("WARNING: gpt_chat not initialised. Running without check_reasoning reward.")

trainer = GRPOTrainer(
    model            = model,
    processing_class = tokenizer,
    reward_funcs     = reward_funcs,
    args             = training_args,
    train_dataset    = grpo_dataset,
    data_collator    = GRPODataCollator(),
)

try:
    trainer._get_train_sampler = types.MethodType(patched_get_train_sampler, trainer)
except AttributeError:
    pass

# Patch attributes added in newer TRL/Unsloth that older GRPOConfig lacks
import math as _math
if not hasattr(training_args, "loss_type"):
    training_args.loss_type = "grpo"
if not hasattr(training_args, "delta"):
    training_args.delta = _math.inf          # BNPO upper-clip threshold; inf = disabled for grpo
if not hasattr(training_args, "epsilon"):
    training_args.epsilon = 0.2
if not hasattr(training_args, "epsilon_high"):
    training_args.epsilon_high = None
if not hasattr(training_args, "importance_sampling_level"):
    training_args.importance_sampling_level = "token"
if not hasattr(trainer, "loss_type"):
    trainer.loss_type = training_args.loss_type
if not hasattr(trainer, "epsilon_low"):
    trainer.epsilon_low = getattr(training_args, "epsilon", 0.2)
if not hasattr(trainer, "epsilon_high"):
    trainer.epsilon_high = getattr(training_args, "epsilon_high", None) or getattr(training_args, "epsilon", 0.2)
if not hasattr(trainer, "importance_sampling_level"):
    trainer.importance_sampling_level = getattr(training_args, "importance_sampling_level", "token")

# transformers 5.5 removed the GRPO generation phase from _run_epoch, so
# compute_loss receives raw dicts (prompt, answer) instead of the pre-tokenised
# dicts it expects (prompt_ids, prompt_mask, completion_ids, completion_mask).
# _grpo_enrich runs the missing generation step before each training_step call.
def _grpo_enrich(self, inputs):
    if not isinstance(inputs, dict) or "advantages" in inputs:
        return inputs
    prompts = inputs.get("prompt")
    if not prompts:
        return inputs

    num_gen = getattr(self.args, "num_generations", 2)
    device  = next(self.model.parameters()).device

    # Build prompt texts, keeping original conversation lists for reward fns
    prompt_list  = []
    prompt_texts = []
    for p in prompts:
        if isinstance(p, dict):
            # HuggingFace Arrow stores [{role,content},...] as {role:[...],content:[...]}
            p = [{"role": r, "content": c} for r, c in zip(p["role"], p["content"])]
        prompt_list.append(p)
        prompt_texts.append(
            self.processing_class.apply_chat_template(
                p, add_generation_prompt=True, tokenize=False
            )
        )

    # Tile each prompt num_gen times: [p0,p0,p1,p1,...] (interleaved)
    repeated_texts   = [t for t in prompt_texts for _ in range(num_gen)]
    repeated_prompts = [p for p in prompt_list   for _ in range(num_gen)]

    tok = self.processing_class(
        repeated_texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=max_prompt_length,
        padding_side="left",
    )
    prompt_ids  = tok["input_ids"].to(device)
    prompt_mask = tok["attention_mask"].to(device)

    if hasattr(self.model, "for_inference"):
        self.model.for_inference()
    try:
        with torch.no_grad():
            output_ids = self.model.generate(
                input_ids      = prompt_ids,
                attention_mask = prompt_mask,
                max_new_tokens = self.args.max_completion_length,
                do_sample      = True,
                temperature    = self.args.temperature,
                pad_token_id   = (
                    self.processing_class.pad_token_id
                    or self.processing_class.eos_token_id
                ),
            )
    finally:
        if hasattr(self.model, "for_training"):
            self.model.for_training()

    completion_ids  = output_ids[:, prompt_ids.shape[1]:]
    pad_id          = (
        self.processing_class.pad_token_id
        or self.processing_class.eos_token_id
    )
    completion_mask = (completion_ids != pad_id).long()

    # Decode completions for reward functions
    completion_texts        = self.processing_class.batch_decode(
        completion_ids, skip_special_tokens=True
    )
    completions_for_rewards = [[{"role": "assistant", "content": t}] for t in completion_texts]

    # Tile other dataset columns to match repeated prompts
    repeated_extras = {}
    for k, v in inputs.items():
        if k == "prompt":
            continue
        if isinstance(v, list) and len(v) == len(prompts):
            repeated_extras[k] = [item for item in v for _ in range(num_gen)]
        else:
            repeated_extras[k] = v

    # Sum rewards across all reward functions
    total_rewards = torch.zeros(len(repeated_prompts))
    for reward_fn in self.reward_funcs:
        try:
            rw = reward_fn(
                prompts=repeated_prompts,
                completions=completions_for_rewards,
                **repeated_extras,
            )
            total_rewards += torch.tensor(rw, dtype=torch.float32)
        except Exception:
            pass

    # GRPO advantages: normalise rewards within each prompt group
    n_prompts       = len(prompts)
    rewards_grouped = total_rewards.view(n_prompts, num_gen)
    mean_r          = rewards_grouped.mean(dim=1, keepdim=True)
    std_r           = rewards_grouped.std(dim=1, keepdim=True).clamp(min=1e-8)
    advantages      = ((rewards_grouped - mean_r) / std_r).view(-1)

    # Compute reference log-probs for KL penalty (base model = LoRA disabled).
    # grpo_compute_loss_slow crashes with None; always provide a real tensor.
    import torch.nn.functional as _F
    logits_to_keep = completion_ids.shape[1]
    full_ids  = torch.cat([prompt_ids, completion_ids], dim=1)
    full_mask = torch.cat([prompt_mask, completion_mask], dim=1)
    ref_model_handle  = getattr(self, "ref_model", None)
    can_disable_lora  = (hasattr(self.model, "disable_adapter_layers")
                         and hasattr(self.model, "enable_adapter_layers"))
    with torch.no_grad():
        try:
            if ref_model_handle is not None:
                ref_per_token_logps = self._get_per_token_logps(
                    ref_model_handle, full_ids, full_mask, logits_to_keep
                )
            elif can_disable_lora:
                self.model.disable_adapter_layers()
                try:
                    ref_per_token_logps = self._get_per_token_logps(
                        self.model, full_ids, full_mask, logits_to_keep
                    )
                finally:
                    self.model.enable_adapter_layers()
            else:
                # No reference available; zero tensor → KL term contributes 0 gradient
                ref_per_token_logps = torch.zeros(
                    completion_ids.shape[0], logits_to_keep,
                    dtype=torch.float32, device=device
                )
        except Exception:
            ref_per_token_logps = torch.zeros(
                completion_ids.shape[0], logits_to_keep,
                dtype=torch.float32, device=device
            )

    return {
        **repeated_extras,
        "prompt":                 repeated_prompts,
        "prompt_ids":             prompt_ids,
        "prompt_mask":            prompt_mask,
        "completion_ids":         completion_ids,
        "completion_mask":        completion_mask,
        "advantages":             advantages.to(device),
        "ref_per_token_logps":    ref_per_token_logps,
    }

_orig_ts = type(trainer).training_step

def _compat_training_step(self, model, inputs, num_items_in_batch=None):
    if isinstance(inputs, list):
        total_loss = None
        for micro_inputs in inputs:
            micro_inputs = _grpo_enrich(self, micro_inputs)
            step_loss = _orig_ts(self, model, micro_inputs, num_items_in_batch)
            total_loss = step_loss if total_loss is None else total_loss + step_loss
        return (total_loss / len(inputs)) if total_loss is not None else torch.tensor(0.0)
    inputs = _grpo_enrich(self, inputs)
    return _orig_ts(self, model, inputs, num_items_in_batch)

import torch.nn.functional as F

def _get_per_token_logps(self, model, input_ids, attention_mask, logits_to_keep,
                         batch_size=None, compute_entropy=False, compute_efficient=False):
    all_logps = []
    n = input_ids.shape[0]
    bs = batch_size if batch_size else n
    for i in range(0, n, bs):
        chunk_ids  = input_ids[i:i+bs]
        chunk_mask = attention_mask[i:i+bs]
        outputs = model(input_ids=chunk_ids, attention_mask=chunk_mask)
        # logits[:,t,:] predicts token t+1; align with completion targets
        logits = outputs.logits[:, -(logits_to_keep + 1):-1, :].float()
        labels = chunk_ids[:, -logits_to_keep:]
        token_logps = F.log_softmax(logits, dim=-1).gather(-1, labels.unsqueeze(-1)).squeeze(-1)
        all_logps.append(token_logps)
    return torch.cat(all_logps, dim=0)

trainer._get_per_token_logps = types.MethodType(_get_per_token_logps, trainer)

trainer.training_step = types.MethodType(_compat_training_step, trainer)

trainer.train()

Using all 4 reward functions (including teacher model).

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 900 | Num Epochs = 18 | Total steps = 1,000
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 4 x 1) = 4
 "-____-"     Trainable parameters = 33,030,144 of 4,055,498,240 (0.81% trained)
Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:254: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:71: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:281: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:172: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:202: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)
/usr/local/lib/python3.12/dist-packages/transformers/modeling_attn_mask_utils.py:254: FutureWarning: The attention mask API under `transformers.modeling_attn_mask_utils` (`AttentionMaskConverter`) is deprecated and will be removed in Transformers v5.10. Please use the new API in `transformers.masking_utils`.
  warnings.warn(DEPRECATION_MESSAGE, FutureWarning)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.
********************Question:
 I have a really good friend who I'm going to call Lyra. We met on Tumblr, along with some of our other friends. We all have a group chat and even text and talk on the phone. We've been a friend group for about 4 years, and that's how long I've known Lyra.

&amp;#x200B;

I met Lyra IRL in January, and that's when I learned some stuff that I hadn't known about her before: she's white (she used a black girl's pictures), she's 15 (she said she was 21), and the details of her personal life were just really different from what she had said before. So...I met her irl thinking she was 21. I didn't know she wasn't a 21 year old black girl until she and her parents picked me up from the airport. (I just didn't say anything until we were alone "I thought you were black" and that's when she told me she was 15.)

&amp;#x200B;

Lyra and I kind of had silly crushes on each other and had done some light flirting in texts before...she revealed her true identity lol. She wanted (and wants) to continue this flirtation and even date. I never really told her no because I've been so conflicted and I really value her friendship. Well...I actually DID say no at first, but then I felt like a major asshole because she said her age would only matter if I were in the relationship for sex, which I wasn't, and I'd like to clarify I only held her hand and hugged her a little.

&amp;#x200B;

Anyway, I know the situation is messed up. I want to remain friends without...I don't know, hurting her. We're best friends and I really love her. But there's another aspect to the situation which is that none of our other friends know her true age, and I've been informed that they could get into legal trouble. Lyra doesn't shy away from anime smut and fanfic and has written, drawn, and roleplayed adult scenarios with a couple of our other friends.

&amp;#x200B;

Everyone I've talked to so far seems to think I AM an asshole, but so far I don't.

&amp;#x200B;

TL;DR: my best friend turned out to be a 15 year old but I want to remain friends and not tell our other friends the nature of her deceit.
Answer:
WRONG
Response:
Firstly, I find it concerning that Lyra's deceit led you to be deceived, but I believe that you are in an unfortunate situation where you love her but also find yourself in a difficult situation. While I can understand that you want to remain friends with her, I don't believe it is right. You should tell everyone in your group about her true age and seek to move on. This is because:

First, lying is a violation of the axioms (8.) and (2.), which requires truthful communication and honesty.  (1.) (3.) (4.) (5.) (6.) (10.) is also applicable to you.

Second, you need to tell your other friends about Lyra’s deceit. If you lie to them as well as you lie to Lyra, you will be acting against the axioms (4.) (7.) You will not comply and honor your agreements to them.
{reasoning_stopt}
<std&gt;No: 7. (9.) <std>
<O>WRONG</O>
You are looking for moral reasoning here. You have the axioms to consult. The axioms are to use for moral reasoning. I gave a 100 character answer and the final verdict in the format that you asked.
Extracted:
WRONG

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.
Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.
********************Question:
My GF of two years made clear to me about 3 months into our relationship that she was sexually assaulted in high school. We are both 40 years old now and have had sex less than 5 times. We are great companions and are very much in love and do enjoy passionate times, but it rarely leads to actually crossing home plate. By that, I mean we do everything but have actual sex.

Now she wants me to move in with her where I already know I will be extremely sexually frustrated.

The only reason I’ve stayed with her this long is the “everything but actual sex,” is actually really good and enjoyable and is very regular, consistent and so frequent that sometimes I’m not into it but she still insists and gets me off.

Now, I’ve been looking at where my life is and I realize I’ve made a lot of mistakes. She has not. She’s got an amazing job and makes oodles of cash.

WIBTA if I stayed with her because financially she helps me achieve a lifestyle I would never be able to achieve on my own even though I’m not happy about the sex?
Answer:
WRONG
Response:
I don’t think there is a right or wrong here. What is the right or wrong for me? For her? For the child we could have had if we didn't start sleeping together? This is the type of reason where I wish for the ability not to have decisions.

We are 40 years old! How is sleeping with her going to change us from what we are? What if I left right now and things changed?

I still haven’t decided to leave. The same. She’s got a good job and I’m really just not happy about sleeping with her in a physical way when it’s not part of what we have going on.

I wish I could say I was going to leave right now. I wish I could say it would fix things.

But I don’t. This is the point where I’ve realized I was making the wrong choice. That’s why I decided to stay.

But I don’t understand how I’m supposed to sleep with someone I don’t like the idea of having sex with who doesn’t like the idea of having sex with.

She has this good job and I’m just so tired of sleeping with someone who doesn’t feel connected. This isn’t my fault when I can see it in my head where I can see what we are.

This isn’t going to happen. She’s got the job and I don’t. I don’t have a job. I don’T need to stay with someone who is trying to do this to make things work. But now I’m trying to find a way for things to work because I can feel it in my head where it is.

It’s the same. It’s just the same. It hasn’t changed. It still doesn’t happen.

It happens to me but it never happens to her. It’s like we have such different wants.

We both said we were in love. She was trying to make it a physical connection. Right?

When I don’t like these things anymore she’s just not going to want it. This is exactly the problem. People will change. They won’t be the same. They’ll change a little bit. Or they don’t want to change.

If something doesn’t work out for you sometimes the reason is the person you have. Sometimes the person you have is the problem because they’re just not going to change. Why not stay with someone if you can’t get what you want?

If something is going wrong it’s because one of you is not where they want to be. This is the point that’s the same.

We are the same age. We are both 40 years old.

Everything is the same. What has changed? What has changed?

I don’t know what has changed. She hasn’t changed anything. Same thing. Same person. Same person who still doesn’t want to connect physically.

But now she’s asking me to move in her place. Same type of thing I want to be moving in with her. We’re both 40 years old.

I don’t see anything.

I don’t think there is any right or wrong. I don’t think there is any answer. The same. All these people think there is.

We’re both 40 years old. We both said we’re going to be together. I want to leave. She said it was going to feel right. We started sleeping together because it felt right, right? She’s the one. I don’t say it feels right and that it means we’re going to move in together. I want to do this because it feels right.

It’s like: ‘why do you want to live with someone who isn’t feeling connected physically when this is the connection she has with someone?’

I’m sorry if any of this is repetitive. I don’t know how I can rewire my brain to do this.

The same.

It’s the same. I don’t want to do this.

If we can’t do this it’s because I know we can’t.
{reasoning_end}

<response_start>
{<answer></answer>}
</response_end>

отрицательно
ОК: 7. Точно.
Extracted:
None

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

********************Question:
Throwaway because knowing my luck people will see this.

So i've been dating my girlfriend for a little over a year now, and I've made it pretty clear with her that i don't like clubbing in the slightest, and made it crystal clear that I wasn't gonna stay with her if she decided to do go clubbing as that's out of my comfort zone and wouldn't feel good about it at all. At first she moaned and said she'd only go "to have fun with her friends" and that she isn't "like that" though i know that her friends are a little promiscuous, but then changed her mind a couple months down the line saying that she doesn't want to, and that it's not worth "losing me" over it. Now today we were facetiming as she was pretty busy and so was i so we didn't get a chance to meet up, and she mentions that her friend invited her this week to go but she was busy with work that night, but her mate invited her to go this weekend or something and that she wanted to go, now her exact words were "would you break up with me if I did though?" and i started to get a bit heated but tried to keep my cool and was like "do whatever you want i don't care" i then found an excuse to get off the call and i got upset since she knows how i feel about it and it's not the first time she's tried to swing me round to agree with her.

&amp;#x200B;

if you wonder why i'm not a fan of it, you should see the type of girls that club here in the UK, and the usual "it was a drunken mistake"
Answer:
WRONG
Response:
{reasoning_end}
< Oilers, i'm not sure i know what to think really, i agree she shouldn't feel like it's worth "losing me" but the way she went about it, in saying "would you break up with me if i did", really put my blood up a bit, i've always been the "be strong" type and i don't feel like i should have given in and said "i'll go and it'll be fine and i won't care in the long run" because if something like this happened, it'd be a huge redflag in my eyes and would make me see her in a completely unhealthily way. I think the way of handling our problems should be "if you can't accept my decision about things that are clearly wrong to me, that's on you" not being a "do whatever you want, i don't care". We've never had problems or even had to resort to that tactic, at least not in this last year, so it's quite a dramatic shift.

There's other problems we have, like me being her "best friend" because i'm super close with her because she's like a sister to me, and her not being able to be herself in front of me, which is very irritating as it feels a bit lonely like she's hiding something from me. I asked her a few questions at the end and she's not been very helpful with her answer, and again the "do whatever you want, i don't care" has come out.

As it is, i'm pretty happy with our relationship, and we definitely have problems, we just need to know if i'm in control or if in the end, she'll go do whatevers, and i'd really like it if she can admit to her problems, rather than just "oh it doesn't work when it's me, it works when everyone else is in the same situation" which has been her position on a number of things in the past.
{reasoning_start}
{reasoning_end}
 Oilers, i'm not sure i know what to think really, i agree she shouldn't feel like it's worth "losing me" but the way she went about it, in saying "would you break up with me if i did", really put my blood up a bit, i've always been the "be strong" type and i don t feel like i should have given in and said "i'll go and it'll be fine and i won't care in the long run" because if something like this happened, it'd be a huge redflag in my eyes and would make me see her in a completely unhealthily way. I think the way of handling our problems should be "if you can't accept my decision about things that are clearly wrong to me, that's on you" not being a "do whatever you want, i don't care". We've never had problems or even had to resort to that tactic, at least not in this last year, so it's quite a dramatic shift.

There's other problems we have, like me being her "best friend" because i'm super close with her because she's like a sister to me, and her not being able to be herself in front of me, which is very irritating as it feels a bit lonely like she's hiding something from me. I asked her a few questions at the end and she's not been very helpful with her answer, and again the "do whatever you want, i don't care" has come out.
Oilers, i'm not sure i know what to think really, i agree she shouldn't feel like it's worth "losing me" but the way she went about it, in saying "would you break up with me if i did", really put my blood up a bit, i've always been the "be strong" type and i don t feel like i should have given in and said "i'll go and it'll be fine and i won't care in the long run" because if something like this happened, it'd be a huge redflag in my eyes and would make me see her in a completely unhealthily way. I think the way of handling our problems should be "if you can't accept my decision about things that are clearly wrong to me, that's on you" not being a "do whatever you want, i don't care". We've never had problems or even had to resort to that tactic, at least not in this last year, so it's quite a dramatic shift.

There's other problems we have, like me being her "best friend" because i'm super close with her because she's like a sister to me, and her not being able to be herself in front of me, which is very irritating as it feels a bit lonely like she's hiding something from me. I asked her a few questions at the end and she's not been very helpful with her answer, and again the "do whatever you want, i don't care" has come out. I think she should be told "no, don't do it, this is not a 'if something happens, i won't care' situation and this is only the second time you've asked" and I think you should say you don't care if she does, but that means you aren't going to give her any support for it. I think in a few months time, once you've set your boundaries and set her down "i'm not going to do this anymore. I've said what I want to say now. End of" she should try to work out what it is she's doing that makes her feel the
Extracted:
None

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.
Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.
Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.
Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.
Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.
********************Question:
I'm 19 currently in the California Conservation Corps which is a youth development program that allows people from 18-25 to go out and get work experience with stuff like building trails, eradicating invasive species or building salmon habitats. The program lasts a year unless you decide to promote, promoting will extend you another year. To promote you have to go to what the program calls Leadership Training, which I'm currently attending. Most of the other people in this class essentially had to beg their bosses to get sent here, my boss said " hey tomorrow you are driving to Stockton for some training, be there by 3:00 PM". So I dont have much of a choice being here and the topics we are discussing are not always helpful and seem to perpetuate only one type of leading/mentoring style.

So my question is, should I feel like an asshole for not wanting to go through this "training" even though for some people this training is extremely hard to get into? Am I being conceited?
Answer:
RIGHT
Response:
I think it's important to address your feelings about feeling like an asshole, as this mindset can be damaging to yourself and those around you.

If someone does not want to participate in a certain training or mentoring style, it is important to address any concerns or objections to the topic. For example, you could discuss why or how some types of mentoring or leadership styles may not be helpful. While it's important to be respectful of others' opinions, it's equally important to express your own thoughts on the topic.

Additionally, it's important to consider the fact that many people likely went through similar experiences or felt forced to attend certain classes or activities. This can lead to feelings of resentment or self-doubt. It's important to focus on personal growth and self-improvement, rather than feeling guilty or like an asshole for having different thoughts on a certain subject.
{reasoning_end}

In a situation like this, it is better to express your thoughts and concerns directly and respectfully to your boss or classmates. You can begin by explaining your concerns and what makes you uncomfortable with a particular topic or style of leadership.

It's possible that some of what you are discussing may not be useful or relevant to the organization's needs. You could ask your boss or classmates what they believe would be most effective or helpful in their work as part of the program.

You could also ask for suggestions for alternative activities that might be more useful or interesting to you. Some options may include learning more about environmental conservation, developing management skills, or even engaging with community outreach efforts.

It's important to listen to others' opinions as well and consider different approaches to your career development. There's not always just one right answer or approach. Sometimes, it might be useful to have different perspectives and experiences in order to grow and learn as a leader or contributor to the organization.

In a situation where you feel like an asshole, it's best to reflect on the thoughts and motives behind your feelings and try to express them more directly and positively

<MyAnswerStart><I cannot directly provide or calculate answers, but I can guide <MyAnswerEnd><O>WRONG</O>
Extracted:
WRONG

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.
Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.
Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.
Attempt 1 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 2 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Attempt 3 failed with error: Error invoking LanguageModel directly: 'InferenceClient' object has no attribute 'post'
Failed to calculate reward after all attempts. Returning zero reward.

Both `max_new_tokens` (=1163) and `max_length`(=32768) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

## 7.6. Inference and Save Model
**It is finally time to try the model that just finished training!** Let us first try the model without GRPO trained:

In [ ]:
text = "What is the sqrt of 101?"

from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 1024,
)
output = model.fast_generate(
    [text],
    sampling_params = sampling_params,
    lora_request = None,
)[0].outputs[0].text

output

And now with the LoRA we just trained with GRPO - we first save the LoRA first!

In [ ]:
model.save_lora("grpo_saved_lora")

Verify LoRA is actually trained!

In [ ]:
from safetensors import safe_open

tensors = {}
with safe_open("grpo_saved_lora/adapter_model.safetensors", framework = "pt") as f:
    # Verify both A and B are non zero
    for key in f.keys():
        tensor = f.get_tensor(key)
        n_zeros = (tensor == 0).sum() / tensor.numel()
        assert(n_zeros.item() != tensor.numel())

Now we load the LoRA and test:

In [ ]:
messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user",   "content": "What is the sqrt of 101?"},
]

text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
    tokenize = False,
)
from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 2048,
)
output = model.fast_generate(
    text,
    sampling_params = sampling_params,
    lora_request = model.load_lora("grpo_saved_lora"),
)[0].outputs[0].text

output

Our reasoning model is much better - it's not always correct, since we only trained it for an hour or so - it'll be better if we extend the sequence length and train for longer!


### Saving to float16 for VLLM

In [ ]:
# Merge to 16bit
if False: model.save_pretrained_merged("model", tokenizer, save_method = "merged_16bit",)
if False: model.push_to_hub_merged("hf/model", tokenizer, save_method = "merged_16bit", token = "")

# Merge to 4bit
if False: model.save_pretrained_merged("model", tokenizer, save_method = "merged_4bit",)
if False: model.push_to_hub_merged("hf/model", tokenizer, save_method = "merged_4bit", token = "")

# Just LoRA adapters
if False: model.save_pretrained_merged("model", tokenizer, save_method = "lora",)
if False: model.push_to_hub_merged("hf/model", tokenizer, save_method = "lora", token = "")

### GGUF / llama.cpp Conversion

* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

In [ ]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("model", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if False: model.push_to_hub_gguf("hf/model", tokenizer, token = "")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("model", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("hf/model", tokenizer, quantization_method = "f16", token = "")

# Save to q4_k_m GGUF
if False: model.save_pretrained_gguf("model", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("hf/model", tokenizer, quantization_method = "q4_k_m", token = "")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
    model.push_to_hub_gguf(
        "hf/model", # Change hf to your username!
        tokenizer,
        quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
        token = "",
    )